"""
"Did you know?" trivia cards used as a rotation option during ad blocks.

Kept local (no network) because the device is expected to run offline for
24+ hours. Each fact is short enough to read during a typical 30s ad break.

Format: (title, body)
  - title: one-line hook
  - body:  the fact itself, may contain a \\n to split into two readable lines

Render path in src/ad_blocker.py::_get_blocking_text.
"""

# Keep entries concise — the blocking overlay renders at large text size and
# only a few lines fit comfortably at 1080p / 4K. Prefer two short lines of
# body over one long line.
DID_YOU_KNOW = [
    ("Bananas are berries",
     "Botanically speaking, bananas are berries.\nStrawberries, despite the name, are not."),
    ("Honey never spoils",
     "Edible honey was found in Egyptian tombs,\nstill good after 3000 years."),
    ("Octopuses have 3 hearts",
     "Two pump blood to the gills, one pumps to the body.\nThe body heart stops when they swim."),
    ("Sharks predate trees",
     "Sharks have existed for ~400 million years.\nTrees showed up roughly 350 million years ago."),
    ("Venus spins backwards",
     "The sun rises in the west on Venus.\nIts day is also longer than its year."),
    ("A day on Mercury",
     "One Mercury day equals about 59 Earth days,\nbut one Mercury year is only 88 Earth days."),
    ("Eiffel Tower grows",
     "The Eiffel Tower can be ~15 cm taller in summer.\nMetal expands with heat."),
    ("Cleopatra's era",
     "Cleopatra lived closer in time to the first Moon\nlanding than to the building of the Great Pyramid."),
    ("T. rex and Stegosaurus",
     "Tyrannosaurus lived closer to us in time\nthan it did to Stegosaurus."),
    ("Wombat cube poop",
     "Wombats are the only animals known to produce\ncube-shaped droppings."),
    ("Great Wall from space?",
     "Despite the myth, the Great Wall of China is not\nnormally visible from space by the naked eye."),
    ("Golf balls on the Moon",
     "Alan Shepard hit two golf balls on the Moon\nduring Apollo 14 in 1971."),
    ("Bubble wrap's first job",
     "Bubble wrap was originally invented in 1957\nas textured wallpaper. It flopped."),
    ("Saturn would float",
     "Saturn's density is less than water.\nGiven a big enough bathtub, it would float."),
    ("Antarctica has no time zone",
     "Bases on Antarctica use whichever time zone\nmatches the country that operates them."),
    ("Fastest muscle",
     "The human eye's external muscles are among\nthe fastest reacting muscles in the body."),
    ("Slowest glacier",
     "Most glaciers crawl at a few meters per year.\nSome surge hundreds of meters in weeks."),
    ("A group of flamingos",
     "...is called a 'flamboyance'.\nA group of crows is a 'murder'."),
    ("Cows have best friends",
     "Studies show cows form pair-bonds and get stressed\nwhen separated from their preferred partner."),
    ("Your stomach regrows",
     "The stomach lining replaces itself roughly\nevery 3 to 4 days to resist its own acid."),
    ("Finger bones",
     "Every finger except the thumb has three bones.\nThumbs have only two."),
    ("Goldfish memory myth",
     "Goldfish can actually remember things for\nmonths, not seconds."),
    ("Pineapple origin",
     "Pineapples are native to South America,\nnot Hawaii."),
    ("Lightning temperature",
     "A lightning bolt can reach 30,000 Kelvin,\nabout five times hotter than the Sun's surface."),
    ("Sound under water",
     "Sound travels roughly four times faster in water\nthan it does in air."),
    ("Human DNA and banana",
     "Humans share about 60% of our DNA\nwith bananas. Chimps: ~98%."),
    ("Sneezing speed",
     "A sneeze can push air out of the nose\nat speeds over 160 km/h."),
    ("Deepest ocean trench",
     "The Mariana Trench's Challenger Deep\nis about 11 km below sea level."),
    ("Hottest planet",
     "Venus, not Mercury, is the hottest planet\nin our solar system thanks to its thick CO2."),
    ("Moon drift",
     "The Moon moves about 3.8 cm farther from Earth\neach year."),
    ("First web page",
     "The first-ever web page (1991) is still\nreachable at CERN's site."),
    ("Tallest tree",
     "Hyperion, a coast redwood in California,\nis over 115 m tall. Its location is secret."),
    ("Octopus DNA edits",
     "Octopuses edit their own RNA in real time,\nwhich is extremely rare among animals."),
    ("Platypus milk",
     "Platypus mothers sweat milk through their skin;\nthey have no nipples."),
    ("Hairless cat gene",
     "The Sphynx cat's hairlessness is caused by\na single recessive gene."),
    ("Heaviest organ",
     "The liver is the heaviest internal organ,\nroughly 1.5 kg in adults."),
    ("Largest desert",
     "The largest desert on Earth is Antarctica —\ncold deserts count too."),
    ("Oldest continuously inhabited city",
     "Damascus, Syria has been continuously\ninhabited for around 11,000 years."),
    ("Nobel Peace Prize & T-shirts",
     "The Nobel Peace Prize medal is made of\nrecycled gold from other medals since 2012."),
    ("Human body cells",
     "Your body contains roughly 37 trillion cells.\nIt also hosts more bacteria than cells."),
    ("Eels vs whales",
     "Electric eels can generate about 600 V,\nenough to stun a horse briefly."),
    ("Cashew cousin",
     "Cashews and mangoes are botanical cousins.\nBoth can cause contact dermatitis in some people."),
    ("Koala fingerprints",
     "Koala fingerprints are almost indistinguishable\nfrom human ones, even under a microscope."),
    ("Tomato = fruit",
     "Botanically a fruit, legally a vegetable —\nthe US Supreme Court ruled on it in 1893."),
    ("Blue whale heart",
     "A blue whale's heart is about the size of\na small car and can weigh 400+ kg."),
    ("Hummingbird wings",
     "Hummingbirds beat their wings roughly\n50 to 80 times per second."),
    ("Dolphin names",
     "Dolphins use 'signature whistles' that work\nlike personal names for each individual."),
    ("Neutron star density",
     "One sugar-cube worth of neutron star material\nwould weigh about a billion tons on Earth."),
    ("Sahara was green",
     "The Sahara was green grassland and lakes\nabout 6,000 years ago."),
    ("Reddest place on Earth",
     "Lake Natron in Tanzania can turn flamingos\npink and calcify animals that fall in."),
    ("Mount Everest grows",
     "Mount Everest rises about 4 mm per year\ndue to tectonic uplift."),
    ("Milky Way stars",
     "Our galaxy holds an estimated 100 to 400\nbillion stars."),
    ("A billion seconds",
     "A billion seconds is just under 32 years.\nA trillion seconds is about 31,700 years."),
    ("Great Barrier Reef",
     "It's the largest living structure on Earth\nand is visible from low-Earth orbit."),
    ("Snail sleep",
     "Garden snails can sleep for up to three years\nif conditions are unfavourable."),
    ("Penguin proposals",
     "Gentoo penguins 'propose' with a pebble.\nThe partner's acceptance seals the pair bond."),
    ("Octopus camouflage",
     "Octopuses can change color despite being\ncolorblind. Cells in the skin likely sense light."),
    ("Kangaroo joey",
     "A newborn kangaroo is about the size\nof a jellybean."),
    ("Mosquito preference",
     "Mosquitoes are more attracted to people\nwith Type O blood on average."),
    ("Cat nose prints",
     "A cat's nose pattern is as unique as\na human fingerprint."),
    ("Elephant grief",
     "Elephants are known to mourn their dead\nand revisit bones of herd members."),
    ("Bamboo growth",
     "Some species of bamboo grow up to 90 cm\nper day under perfect conditions."),
    ("Eiffel Tower marriage",
     "Erika Eiffel, an American woman, married\nthe Eiffel Tower in a 2007 ceremony."),
    ("No two zebras match",
     "No two zebras have exactly the same\nstripe pattern."),
    ("Sloth digestion",
     "A sloth can take up to a month to fully\ndigest a single meal."),
    ("Crows hold grudges",
     "Crows can remember a face that threatened\nthem and warn other crows about it."),
    ("Fire's temperature",
     "A candle flame's hottest point is the tip\nof the blue inner cone, around 1400 C."),
    ("Rainbows at night",
     "Yes, there are 'moonbows', visible when the\nmoon is bright enough behind rain."),
    ("Water memory of the Earth",
     "The water you drink today has cycled\nthrough dinosaurs and ancient oceans."),
    ("Largest living thing",
     "A single 'humongous fungus' in Oregon covers\nabout 9.6 km^2 underground."),
    ("Apple varieties",
     "There are more than 7,500 known apple\nvarieties grown around the world."),
    ("Morse code speed",
     "Skilled telegraphers can send and receive\nMorse at 35+ words per minute by ear."),
    ("Honey badger diet",
     "The honey badger can tolerate bee stings,\nsnake venom, and porcupine quills."),
    ("Fastest land animal",
     "Cheetahs accelerate to 100 km/h in about\n3 seconds but sprint for only ~30 seconds."),
    ("Bees see UV",
     "Many flowers have UV 'nectar guides'\nthat are invisible to human eyes."),
    ("Oldest language still spoken",
     "Tamil has a continuous literary record\ngoing back more than 2,000 years."),
    ("Napping standing up",
     "Horses, cows, and flamingos can sleep\nwhile standing, thanks to a 'stay' mechanism."),
    ("No mirrors in space",
     "Astronauts on the ISS report that water\nforms spheres because there's no 'down'."),
    ("Dust in your home",
     "Most of household dust is shed human skin\nand fibers from clothing and bedding."),
    ("Humans are bioluminescent",
     "We emit extremely faint visible light, ~1000\ntimes below the eye's sensitivity threshold."),
    ("Pigeons as postal workers",
     "Homing pigeons carried mail from the front\nlines in both world wars."),
    ("Ocean unexplored",
     "More than 80% of the ocean remains\nunmapped and unexplored."),
    ("Water freezes faster when hot?",
     "The Mpemba effect: sometimes hot water\nfreezes faster than cold. Still debated."),
    ("Cats purr at healing frequencies",
     "Cat purrs fall in a 20-140 Hz range\nlinked to bone and tissue regeneration."),
]


__all__ = ["DID_YOU_KNOW"]
