"""
Spanish vocabulary for ad blocking overlays.

Contains beginner and intermediate level Spanish words and phrases
displayed during ad blocks to help users practice Spanish.

Format: (spanish, pronunciation, english, example_sentence)
Pronunciation uses simplified phonetics: capitals indicate stressed syllables
"""

# Spanish vocabulary - beginner and intermediate level
SPANISH_VOCABULARY = [
    # ═══════════════════════════════════════════════════════════════════
    # COMMON VERBS (Beginner)
    # ═══════════════════════════════════════════════════════════════════
    ("hablar", "ah-BLAR", "to speak", "Hablo espanol todos los dias."),
    ("comer", "koh-MEHR", "to eat", "Vamos a comer tacos."),
    ("vivir", "bee-BEER", "to live", "Vivo en una ciudad grande."),
    ("ser", "sehr", "to be (permanent)", "Soy de Mexico."),
    ("estar", "ehs-TAR", "to be (temporary)", "Estoy cansado hoy."),
    ("tener", "teh-NEHR", "to have", "Tengo dos hermanos."),
    ("hacer", "ah-SEHR", "to do/make", "Hago la tarea cada noche."),
    ("ir", "eer", "to go", "Voy al supermercado."),
    ("poder", "poh-DEHR", "to be able to/can", "Puedo ayudarte manana."),
    ("querer", "keh-REHR", "to want/love", "Quiero aprender mas."),
    ("saber", "sah-BEHR", "to know (facts)", "Se la respuesta."),
    ("conocer", "koh-noh-SEHR", "to know (people/places)", "Conozco a tu hermana."),
    ("decir", "deh-SEER", "to say/tell", "Dime la verdad."),
    ("venir", "beh-NEER", "to come", "Ven a mi casa."),
    ("salir", "sah-LEER", "to leave/go out", "Salgo a las ocho."),
    ("llegar", "yeh-GAR", "to arrive", "Llego tarde al trabajo."),
    ("poner", "poh-NEHR", "to put/place", "Pon los libros en la mesa."),
    ("dar", "dar", "to give", "Te doy un regalo."),
    ("ver", "behr", "to see", "Veo una pelicula."),
    ("pensar", "pehn-SAR", "to think", "Pienso en ti."),
    ("creer", "kreh-EHR", "to believe", "Creo que tienes razon."),
    ("encontrar", "ehn-kohn-TRAR", "to find", "Encontre mis llaves."),
    ("seguir", "seh-GEER", "to follow/continue", "Sigue todo recto."),
    ("llamar", "yah-MAR", "to call", "Te llamo manana."),
    ("sentir", "sehn-TEER", "to feel", "Siento mucho frio."),
    ("dejar", "deh-HAR", "to leave/let", "Deja la puerta abierta."),
    ("parecer", "pah-reh-SEHR", "to seem", "Parece interesante."),
    ("quedar", "keh-DAR", "to stay/remain", "Me quedo en casa."),
    ("pasar", "pah-SAR", "to pass/happen", "Que paso ayer?"),
    ("esperar", "ehs-peh-RAR", "to wait/hope", "Espero tu respuesta."),
    ("buscar", "boos-KAR", "to look for", "Busco un restaurante."),
    ("entrar", "ehn-TRAR", "to enter", "Entra por la puerta principal."),
    ("trabajar", "trah-bah-HAR", "to work", "Trabajo desde casa."),
    ("necesitar", "neh-seh-see-TAR", "to need", "Necesito tu ayuda."),
    ("llevar", "yeh-BAR", "to carry/wear", "Llevo una camisa azul."),
    ("empezar", "ehm-peh-SAR", "to begin", "Empiezo a las nueve."),
    ("terminar", "tehr-mee-NAR", "to finish", "Termine el proyecto."),
    ("abrir", "ah-BREER", "to open", "Abre la ventana."),
    ("cerrar", "seh-RAR", "to close", "Cierra la puerta."),
    ("escribir", "ehs-kree-BEER", "to write", "Escribo un correo."),
    ("leer", "leh-EHR", "to read", "Leo un libro cada mes."),
    ("dormir", "dohr-MEER", "to sleep", "Duermo ocho horas."),
    ("correr", "koh-REHR", "to run", "Corro en el parque."),
    ("caminar", "kah-mee-NAR", "to walk", "Camino al trabajo."),
    ("comprar", "kohm-PRAR", "to buy", "Compro frutas frescas."),
    ("vender", "behn-DEHR", "to sell", "Vendo mi carro viejo."),
    ("pagar", "pah-GAR", "to pay", "Pago con tarjeta."),
    ("preguntar", "preh-goon-TAR", "to ask", "Pregunto por direcciones."),
    ("responder", "rehs-pohn-DEHR", "to answer", "Respondo rapidamente."),
    ("ayudar", "ah-yoo-DAR", "to help", "Te ayudo con eso."),

    # ═══════════════════════════════════════════════════════════════════
    # COMMON VERBS (Intermediate)
    # ═══════════════════════════════════════════════════════════════════
    ("aprovechar", "ah-proh-beh-CHAR", "to take advantage of", "Hay que aprovechar el tiempo."),
    ("lograr", "loh-GRAR", "to achieve/manage", "Logre terminar el proyecto."),
    ("desarrollar", "deh-sah-roh-YAR", "to develop", "Vamos a desarrollar una app."),
    ("destacar", "dehs-tah-KAR", "to stand out", "Su trabajo destaca por su calidad."),
    ("enfrentar", "ehn-frehn-TAR", "to face/confront", "Debemos enfrentar los problemas."),
    ("realizar", "reh-ah-lee-SAR", "to carry out/accomplish", "Voy a realizar mi sueno."),
    ("averiguar", "ah-beh-ree-GWAR", "to find out", "Necesito averiguar la verdad."),
    ("pertenecer", "pehr-teh-neh-SEHR", "to belong", "Este libro pertenece a Maria."),
    ("alcanzar", "ahl-kahn-SAR", "to reach/achieve", "Quiero alcanzar mis metas."),
    ("surgir", "soor-HEER", "to arise/emerge", "Surgio un problema inesperado."),
    ("tardar", "tar-DAR", "to take time/be late", "Cuanto tardas en llegar?"),
    ("soler", "soh-LEHR", "to usually do", "Suelo desayunar temprano."),
    ("proponer", "proh-poh-NEHR", "to propose", "Propongo una solucion."),
    ("suponer", "soo-poh-NEHR", "to suppose", "Supongo que tienes razon."),
    ("mantener", "mahn-teh-NEHR", "to maintain", "Mantiene una actitud positiva."),
    ("obtener", "ohb-teh-NEHR", "to obtain", "Obtuve buenos resultados."),
    ("reconocer", "reh-koh-noh-SEHR", "to recognize", "Reconozco mi error."),
    ("producir", "proh-doo-SEER", "to produce", "Producimos mucho cafe."),
    ("reducir", "reh-doo-SEER", "to reduce", "Debemos reducir los gastos."),
    ("conducir", "kohn-doo-SEER", "to drive", "Conduzco con cuidado."),
    ("traducir", "trah-doo-SEER", "to translate", "Traduzco documentos."),
    ("elegir", "eh-leh-HEER", "to choose", "Elige tu favorito."),
    ("exigir", "ehk-see-HEER", "to demand", "Exijo una explicacion."),
    ("dirigir", "dee-ree-HEER", "to direct/lead", "Dirijo el proyecto."),
    ("influir", "een-floo-EER", "to influence", "Influye en mi decision."),
    ("contribuir", "kohn-tree-boo-EER", "to contribute", "Contribuyo al equipo."),
    ("construir", "kohns-troo-EER", "to build", "Construyen un edificio nuevo."),
    ("destruir", "dehs-troo-EER", "to destroy", "No destruyas el medio ambiente."),
    ("incluir", "een-kloo-EER", "to include", "Incluye todos los detalles."),
    ("concluir", "kohn-kloo-EER", "to conclude", "Concluyo mi presentacion."),
    ("huir", "oo-EER", "to flee", "Huyen del peligro."),
    ("advertir", "ahd-behr-TEER", "to warn", "Te advierto del riesgo."),
    ("convertir", "kohn-behr-TEER", "to convert", "Convierto dolares a euros."),
    ("invertir", "een-behr-TEER", "to invest", "Invierto en mi educacion."),
    ("divertir", "dee-behr-TEER", "to amuse", "Me divierto con amigos."),
    ("preferir", "preh-feh-REER", "to prefer", "Prefiero el cafe."),
    ("sugerir", "soo-heh-REER", "to suggest", "Sugiero una alternativa."),
    ("mentir", "mehn-TEER", "to lie", "Nunca miento."),
    ("medir", "meh-DEER", "to measure", "Mido la distancia."),
    ("pedir", "peh-DEER", "to ask for/order", "Pido la cuenta."),
    ("repetir", "reh-peh-TEER", "to repeat", "Repite la pregunta."),
    ("competir", "kohm-peh-TEER", "to compete", "Competimos en el torneo."),
    ("servir", "sehr-BEER", "to serve", "Sirvo la cena."),
    ("vestir", "behs-TEER", "to dress", "Me visto rapidamente."),
    ("conseguir", "kohn-seh-GEER", "to get/obtain", "Consegui el trabajo."),
    ("perseguir", "pehr-seh-GEER", "to pursue/chase", "Persigo mis suenos."),
    ("despedir", "dehs-peh-DEER", "to fire/say goodbye", "Me despido de ti."),
    ("impedir", "eem-peh-DEER", "to prevent", "Impido el acceso."),
    ("corregir", "koh-reh-HEER", "to correct", "Corrijo los errores."),
    ("recoger", "reh-koh-HEHR", "to pick up/collect", "Recojo a los ninos."),
    ("proteger", "proh-teh-HEHR", "to protect", "Protejo a mi familia."),
    ("escoger", "ehs-koh-HEHR", "to choose", "Escoge el mejor."),
    ("coger", "koh-HEHR", "to take/catch", "Cojo el autobus."),
    ("valer", "bah-LEHR", "to be worth", "Vale la pena intentar."),
    ("caber", "kah-BEHR", "to fit", "No cabe en la maleta."),
    ("caer", "kah-EHR", "to fall", "Me cai en la calle."),
    ("traer", "trah-EHR", "to bring", "Traigo buenas noticias."),
    ("ofrecer", "oh-freh-SEHR", "to offer", "Ofrezco mi ayuda."),
    ("aparecer", "ah-pah-reh-SEHR", "to appear", "Aparece en la pantalla."),
    ("desaparecer", "deh-sah-pah-reh-SEHR", "to disappear", "Desaparece sin explicacion."),
    ("crecer", "kreh-SEHR", "to grow", "Las plantas crecen rapido."),
    ("agradecer", "ah-grah-deh-SEHR", "to thank", "Agradezco tu ayuda."),
    ("establecer", "ehs-tah-bleh-SEHR", "to establish", "Establezco nuevas metas."),
    ("pertenecer", "pehr-teh-neh-SEHR", "to belong", "Pertenezco a este grupo."),
    ("merecer", "meh-reh-SEHR", "to deserve", "Mereces lo mejor."),
    ("nacer", "nah-SEHR", "to be born", "Naci en primavera."),
    ("obedecer", "oh-beh-deh-SEHR", "to obey", "Obedece las reglas."),

    # ═══════════════════════════════════════════════════════════════════
    # REFLEXIVE VERBS
    # ═══════════════════════════════════════════════════════════════════
    ("levantarse", "leh-bahn-TAR-seh", "to get up", "Me levanto a las siete."),
    ("acostarse", "ah-kohs-TAR-seh", "to go to bed", "Me acuesto temprano."),
    ("despertarse", "dehs-pehr-TAR-seh", "to wake up", "Me despierto con alarma."),
    ("ducharse", "doo-CHAR-seh", "to shower", "Me ducho por la manana."),
    ("banarse", "bah-NYAR-seh", "to bathe", "Me bano en la noche."),
    ("vestirse", "behs-TEER-seh", "to get dressed", "Me visto rapidamente."),
    ("peinarse", "peh-ee-NAR-seh", "to comb one's hair", "Me peino antes de salir."),
    ("lavarse", "lah-BAR-seh", "to wash oneself", "Me lavo las manos."),
    ("cepillarse", "seh-pee-YAR-seh", "to brush", "Me cepillo los dientes."),
    ("maquillarse", "mah-kee-YAR-seh", "to put on makeup", "Me maquillo poco."),
    ("afeitarse", "ah-feh-ee-TAR-seh", "to shave", "Me afeito cada dia."),
    ("sentarse", "sehn-TAR-seh", "to sit down", "Me siento en el sofa."),
    ("quedarse", "keh-DAR-seh", "to stay", "Me quedo en casa hoy."),
    ("irse", "EER-seh", "to leave/go away", "Me voy a las cinco."),
    ("llamarse", "yah-MAR-seh", "to be called", "Me llamo Carlos."),
    ("sentirse", "sehn-TEER-seh", "to feel", "Me siento feliz."),
    ("ponerse", "poh-NEHR-seh", "to put on/become", "Me pongo nervioso."),
    ("quitarse", "kee-TAR-seh", "to take off", "Me quito los zapatos."),
    ("casarse", "kah-SAR-seh", "to get married", "Se casan en junio."),
    ("divorciarse", "dee-bohr-see-AR-seh", "to get divorced", "Se divorciaron el ano pasado."),
    ("mudarse", "moo-DAR-seh", "to move (house)", "Me mudo a otra ciudad."),
    ("quejarse", "keh-HAR-seh", "to complain", "Se queja de todo."),
    ("olvidarse", "ohl-bee-DAR-seh", "to forget", "Me olvide de la cita."),
    ("acordarse", "ah-kohr-DAR-seh", "to remember", "Me acuerdo de ti."),
    ("comprometerse", "kohm-proh-meh-TEHR-seh", "to commit oneself", "Me comprometo a estudiar."),
    ("enterarse", "ehn-teh-RAR-seh", "to find out", "Me entere de la noticia."),
    ("darse cuenta", "DAR-seh KWEHN-tah", "to realize", "Me di cuenta del error."),
    ("equivocarse", "eh-kee-boh-KAR-seh", "to be wrong/make mistake", "Todos nos equivocamos."),
    ("preocuparse", "preh-oh-koo-PAR-seh", "to worry", "No te preocupes por eso."),
    ("arrepentirse", "ah-reh-pehn-TEER-seh", "to regret", "Me arrepiento de esa decision."),
    ("atreverse", "ah-treh-BEHR-seh", "to dare", "Me atrevo a intentarlo."),
    ("quemarse", "keh-MAR-seh", "to burn oneself", "Me queme con el cafe."),
    ("cortarse", "kohr-TAR-seh", "to cut oneself", "Me corte el dedo."),
    ("caerse", "kah-EHR-seh", "to fall down", "Me cai en la escalera."),
    ("romperse", "rohm-PEHR-seh", "to break", "Se rompio el vaso."),
    ("perderse", "pehr-DEHR-seh", "to get lost", "Me perdi en la ciudad."),
    ("aburrirse", "ah-boo-REER-seh", "to get bored", "Me aburro facilmente."),
    ("divertirse", "dee-behr-TEER-seh", "to have fun", "Me divierto mucho."),
    ("enojarse", "eh-noh-HAR-seh", "to get angry", "Me enojo rapidamente."),
    ("calmarse", "kahl-MAR-seh", "to calm down", "Calmate, por favor."),
    ("relajarse", "reh-lah-HAR-seh", "to relax", "Me relajo los fines de semana."),
    ("concentrarse", "kohn-sehn-TRAR-seh", "to concentrate", "Me concentro en el trabajo."),
    ("dedicarse", "deh-dee-KAR-seh", "to dedicate oneself", "Me dedico a la musica."),
    ("acercarse", "ah-sehr-KAR-seh", "to approach", "Me acerco a la puerta."),
    ("alejarse", "ah-leh-HAR-seh", "to move away", "Me alejo del ruido."),

    # ═══════════════════════════════════════════════════════════════════
    # ADJECTIVES (Beginner)
    # ═══════════════════════════════════════════════════════════════════
    ("grande", "GRAHN-deh", "big/large", "Es una casa grande."),
    ("pequeno", "peh-KEH-nyoh", "small", "Tengo un perro pequeno."),
    ("bueno", "BWEH-noh", "good", "Es un buen libro."),
    ("malo", "MAH-loh", "bad", "Hace mal tiempo hoy."),
    ("nuevo", "NWEH-boh", "new", "Compre un carro nuevo."),
    ("viejo", "bee-EH-hoh", "old", "Mi abuelo es viejo."),
    ("joven", "HOH-behn", "young", "Es una mujer joven."),
    ("alto", "AHL-toh", "tall/high", "El edificio es muy alto."),
    ("bajo", "BAH-hoh", "short/low", "El precio esta bajo."),
    ("largo", "LAR-goh", "long", "Es un camino largo."),
    ("corto", "KOHR-toh", "short", "Fue una pelicula corta."),
    ("ancho", "AHN-choh", "wide", "El rio es muy ancho."),
    ("estrecho", "ehs-TREH-choh", "narrow", "La calle es estrecha."),
    ("gordo", "GOHR-doh", "fat", "El gato esta gordo."),
    ("delgado", "dehl-GAH-doh", "thin", "Es muy delgado."),
    ("fuerte", "FWEHR-teh", "strong", "Es un hombre fuerte."),
    ("debil", "DEH-beel", "weak", "Me siento debil hoy."),
    ("rapido", "RAH-pee-doh", "fast", "El tren es muy rapido."),
    ("lento", "LEHN-toh", "slow", "El trafico esta lento."),
    ("facil", "FAH-seel", "easy", "El examen fue facil."),
    ("dificil", "dee-FEE-seel", "difficult", "Es un problema dificil."),
    ("rico", "REE-koh", "rich/delicious", "La comida esta rica."),
    ("pobre", "POH-breh", "poor", "Es una familia pobre."),
    ("caro", "KAH-roh", "expensive", "El hotel es muy caro."),
    ("barato", "bah-RAH-toh", "cheap", "Encontre algo barato."),
    ("limpio", "LEEM-pyoh", "clean", "La casa esta limpia."),
    ("sucio", "SOO-syoh", "dirty", "El piso esta sucio."),
    ("caliente", "kah-LYEHN-teh", "hot", "El cafe esta caliente."),
    ("frio", "FREE-oh", "cold", "El agua esta fria."),
    ("dulce", "DOOL-seh", "sweet", "El pastel es muy dulce."),
    ("salado", "sah-LAH-doh", "salty", "La sopa esta salada."),
    ("amargo", "ah-MAR-goh", "bitter", "El cafe es amargo."),
    ("picante", "pee-KAHN-teh", "spicy", "Me gusta la comida picante."),
    ("feliz", "feh-LEES", "happy", "Estoy muy feliz."),
    ("triste", "TREES-teh", "sad", "Se siente triste hoy."),
    ("cansado", "kahn-SAH-doh", "tired", "Estoy muy cansado."),
    ("enfermo", "ehn-FEHR-moh", "sick", "Mi hijo esta enfermo."),
    ("sano", "SAH-noh", "healthy", "Es importante estar sano."),
    ("ocupado", "oh-koo-PAH-doh", "busy", "Estoy muy ocupado."),
    ("libre", "LEE-breh", "free", "Estas libre manana?"),
    ("lleno", "YEH-noh", "full", "El restaurante esta lleno."),
    ("vacio", "bah-SEE-oh", "empty", "El vaso esta vacio."),
    ("abierto", "ah-BYEHR-toh", "open", "La tienda esta abierta."),
    ("cerrado", "seh-RAH-doh", "closed", "El banco esta cerrado."),
    ("correcto", "koh-REHK-toh", "correct", "Tu respuesta es correcta."),
    ("incorrecto", "een-koh-REHK-toh", "incorrect", "Eso es incorrecto."),
    ("seguro", "seh-GOO-roh", "safe/sure", "Estoy seguro de eso."),
    ("peligroso", "peh-lee-GROH-soh", "dangerous", "Es un lugar peligroso."),
    ("importante", "eem-pohr-TAHN-teh", "important", "Es muy importante."),
    ("interesante", "een-teh-reh-SAHN-teh", "interesting", "El libro es interesante."),

    # ═══════════════════════════════════════════════════════════════════
    # ADJECTIVES (Intermediate)
    # ═══════════════════════════════════════════════════════════════════
    ("disponible", "dees-poh-NEE-bleh", "available", "El doctor esta disponible manana."),
    ("imprescindible", "eem-prehs-seen-DEE-bleh", "essential/indispensable", "El agua es imprescindible."),
    ("agotado", "ah-goh-TAH-doh", "exhausted/sold out", "Estoy agotado despues del trabajo."),
    ("capaz", "kah-PAHS", "capable", "Eres capaz de hacerlo."),
    ("dispuesto", "dees-PWEHS-toh", "willing/ready", "Estoy dispuesto a ayudar."),
    ("actual", "ahk-TWAHL", "current (not actual!)", "La situacion actual es dificil."),
    ("adecuado", "ah-deh-KWAH-doh", "adequate/suitable", "Es el momento adecuado."),
    ("amplio", "AHM-plyoh", "wide/spacious", "Tiene un amplio conocimiento."),
    ("complicado", "kohm-plee-KAH-doh", "complicated", "Es un tema complicado."),
    ("sencillo", "sehn-SEE-yoh", "simple", "La solucion es sencilla."),
    ("profundo", "proh-FOON-doh", "deep", "Es un pensamiento profundo."),
    ("superficial", "soo-pehr-fee-SYAHL", "superficial", "Fue un analisis superficial."),
    ("valioso", "bah-LYOH-soh", "valuable", "Es un objeto muy valioso."),
    ("util", "OO-teel", "useful", "Es una herramienta util."),
    ("inutil", "ee-NOO-teel", "useless", "Es completamente inutil."),
    ("obvio", "OHB-byoh", "obvious", "Es algo obvio."),
    ("curioso", "koo-RYOH-soh", "curious", "Soy muy curioso."),
    ("gracioso", "grah-SYOH-soh", "funny", "Es muy gracioso."),
    ("serio", "SEH-ryoh", "serious", "Es un asunto serio."),
    ("tranquilo", "trahn-KEE-loh", "calm/quiet", "El lugar es muy tranquilo."),
    ("ruidoso", "rrwee-DOH-soh", "noisy", "La calle es ruidosa."),
    ("orgulloso", "ohr-goo-YOH-soh", "proud", "Estoy orgulloso de ti."),
    ("avergonzado", "ah-behr-gohn-SAH-doh", "embarrassed", "Estoy avergonzado."),
    ("emocionado", "eh-moh-syoh-NAH-doh", "excited", "Estoy emocionado por el viaje."),
    ("preocupado", "preh-oh-koo-PAH-doh", "worried", "Estoy preocupado por el examen."),
    ("sorprendido", "sohr-prehn-DEE-doh", "surprised", "Estoy muy sorprendido."),
    ("confundido", "kohn-foon-DEE-doh", "confused", "Estoy confundido."),
    ("decepcionado", "deh-sehp-syoh-NAH-doh", "disappointed", "Estoy decepcionado."),
    ("asustado", "ah-soos-TAH-doh", "scared", "El nino esta asustado."),
    ("celoso", "seh-LOH-soh", "jealous", "Es una persona celosa."),
    ("terco", "TEHR-koh", "stubborn", "Es muy terco."),
    ("timido", "TEE-mee-doh", "shy", "Mi hijo es timido."),
    ("amable", "ah-MAH-bleh", "kind", "Es una persona amable."),
    ("grosero", "groh-SEH-roh", "rude", "No seas grosero."),
    ("educado", "eh-doo-KAH-doh", "polite", "Es muy educado."),
    ("honesto", "oh-NEHS-toh", "honest", "Es una persona honesta."),
    ("sincero", "seen-SEH-roh", "sincere", "Fue un comentario sincero."),
    ("leal", "leh-AHL", "loyal", "Es un amigo leal."),
    ("fiel", "fyehl", "faithful", "Es un perro fiel."),
    ("generoso", "heh-neh-ROH-soh", "generous", "Es muy generoso."),
    ("tacano", "tah-KAH-nyoh", "stingy", "No seas tacano."),
    ("perezoso", "peh-reh-SOH-soh", "lazy", "Soy un poco perezoso."),
    ("trabajador", "trah-bah-hah-DOHR", "hardworking", "Es muy trabajador."),
    ("inteligente", "een-teh-lee-HEHN-teh", "intelligent", "Es muy inteligente."),
    ("listo", "LEES-toh", "smart/ready", "Estas listo para salir?"),
    ("tonto", "TOHN-toh", "silly/stupid", "No seas tonto."),
    ("sabio", "SAH-byoh", "wise", "Mi abuelo es muy sabio."),
    ("culpable", "kool-PAH-bleh", "guilty", "Se siente culpable."),
    ("inocente", "ee-noh-SEHN-teh", "innocent", "Es inocente."),

    # ═══════════════════════════════════════════════════════════════════
    # NOUNS (Common)
    # ═══════════════════════════════════════════════════════════════════
    ("desarrollo", "deh-sah-RROH-yoh", "development", "El desarrollo del proyecto va bien."),
    ("comportamiento", "kohm-pohr-tah-MYEHN-toh", "behavior", "Su comportamiento es extrano."),
    ("conocimiento", "koh-noh-see-MYEHN-toh", "knowledge", "El conocimiento es poder."),
    ("ambiente", "ahm-BYEHN-teh", "environment/atmosphere", "El ambiente es muy agradable."),
    ("herramienta", "eh-rrah-MYEHN-tah", "tool", "Necesito una herramienta."),
    ("recurso", "reh-KOOR-soh", "resource", "Tenemos pocos recursos."),
    ("prueba", "PRWEH-bah", "test/proof", "Necesito una prueba."),
    ("meta", "MEH-tah", "goal", "Mi meta es aprender espanol."),
    ("reto", "RREH-toh", "challenge", "Es un gran reto personal."),
    ("exito", "EHK-see-toh", "success", "El proyecto fue un exito."),
    ("fracaso", "frah-KAH-soh", "failure", "Aprende de tus fracasos."),
    ("ventaja", "behn-TAH-hah", "advantage", "Tenemos una gran ventaja."),
    ("desventaja", "dehs-behn-TAH-hah", "disadvantage", "Es una desventaja clara."),
    ("oportunidad", "oh-pohr-too-nee-DAHD", "opportunity", "Es una buena oportunidad."),
    ("posibilidad", "poh-see-bee-lee-DAHD", "possibility", "Existe esa posibilidad."),
    ("capacidad", "kah-pah-see-DAHD", "capacity/ability", "Tiene mucha capacidad."),
    ("habilidad", "ah-bee-lee-DAHD", "skill/ability", "Es una habilidad importante."),
    ("costumbre", "kohs-TOOM-breh", "custom/habit", "Es una vieja costumbre."),
    ("tradicion", "trah-dee-SYOHN", "tradition", "Es una tradicion familiar."),
    ("cultura", "kool-TOO-rah", "culture", "Me interesa la cultura mexicana."),
    ("historia", "ees-TOH-ryah", "history/story", "Cuenta una historia interesante."),
    ("cuenta", "KWEHN-tah", "account/bill", "Pago la cuenta, por favor."),
    ("cuento", "KWEHN-toh", "story/tale", "Leo un cuento a mis hijos."),
    ("noticia", "noh-TEE-syah", "news", "Es una buena noticia."),
    ("novedad", "noh-beh-DAHD", "novelty/news", "Que novedades hay?"),
    ("asunto", "ah-SOON-toh", "matter/issue", "Es un asunto importante."),
    ("tema", "TEH-mah", "topic/theme", "Cambiemos de tema."),
    ("problema", "proh-BLEH-mah", "problem", "Tengo un problema."),
    ("solucion", "soh-loo-SYOHN", "solution", "Busco una solucion."),
    ("respuesta", "rrehs-PWEHS-tah", "answer", "Necesito una respuesta."),
    ("pregunta", "preh-GOON-tah", "question", "Tengo una pregunta."),
    ("duda", "DOO-dah", "doubt", "No tengo ninguna duda."),
    ("error", "eh-RROHR", "error/mistake", "Cometio un error grave."),
    ("falta", "FAHL-tah", "lack/fault", "Es mi falta."),
    ("culpa", "KOOL-pah", "blame/fault", "No es tu culpa."),
    ("razon", "rrah-SOHN", "reason", "Tienes toda la razon."),
    ("motivo", "moh-TEE-boh", "motive/reason", "Cual es el motivo?"),
    ("causa", "KOW-sah", "cause", "Es la causa del problema."),
    ("efecto", "eh-FEHK-toh", "effect", "Tiene un efecto positivo."),
    ("resultado", "reh-sool-TAH-doh", "result", "El resultado fue bueno."),
    ("cambio", "KAHM-byoh", "change", "Necesito un cambio."),
    ("mejora", "meh-HOH-rah", "improvement", "Se nota la mejora."),
    ("aumento", "ow-MEHN-toh", "increase", "Hubo un aumento de precios."),
    ("disminucion", "dees-mee-noo-SYOHN", "decrease", "Hay una disminucion notable."),
    ("crecimiento", "kreh-see-MYEHN-toh", "growth", "El crecimiento es rapido."),
    ("nivel", "nee-BEHL", "level", "Subio de nivel."),
    ("grado", "GRAH-doh", "degree/grade", "Tiene un alto grado de dificultad."),
    ("medida", "meh-DEE-dah", "measure", "Tomo medidas urgentes."),
    ("paso", "PAH-soh", "step", "Es un paso importante."),
    ("etapa", "eh-TAH-pah", "stage/phase", "Es la primera etapa."),

    # ═══════════════════════════════════════════════════════════════════
    # EXPRESSIONS AND PHRASES
    # ═══════════════════════════════════════════════════════════════════
    ("sin embargo", "seen ehm-BAR-goh", "however/nevertheless", "Es dificil, sin embargo posible."),
    ("a pesar de", "ah peh-SAR deh", "despite/in spite of", "A pesar de todo, sigo adelante."),
    ("de repente", "deh reh-PEHN-teh", "suddenly", "De repente, empezo a llover."),
    ("hoy en dia", "oy ehn DEE-ah", "nowadays", "Hoy en dia todo es digital."),
    ("cada vez mas", "KAH-dah behs mahs", "more and more", "Es cada vez mas dificil."),
    ("hace poco", "AH-seh POH-koh", "a little while ago", "Llegue hace poco."),
    ("a la larga", "ah lah LAR-gah", "in the long run", "A la larga, vale la pena."),
    ("de antemano", "deh ahn-teh-MAH-noh", "beforehand", "Gracias de antemano."),
    ("en cuanto a", "ehn KWAHN-toh ah", "as for/regarding", "En cuanto a eso, no se."),
    ("por lo tanto", "pohr loh TAHN-toh", "therefore", "Por lo tanto, debemos actuar."),
    ("por lo menos", "pohr loh MEH-nohs", "at least", "Por lo menos lo intentaste."),
    ("por supuesto", "pohr soo-PWEHS-toh", "of course", "Por supuesto que si."),
    ("desde luego", "DEHS-deh LWEH-goh", "of course", "Desde luego que puedo."),
    ("en realidad", "ehn reh-ah-lee-DAHD", "actually/in reality", "En realidad, no es asi."),
    ("de hecho", "deh EH-choh", "in fact", "De hecho, tengo razon."),
    ("en cambio", "ehn KAHM-byoh", "on the other hand", "En cambio, el prefiere cafe."),
    ("en vez de", "ehn behs deh", "instead of", "En vez de quejarme, actuare."),
    ("a menudo", "ah meh-NOO-doh", "often", "Voy a menudo al cine."),
    ("de vez en cuando", "deh behs ehn KWAHN-doh", "from time to time", "Como pizza de vez en cuando."),
    ("poco a poco", "POH-koh ah POH-koh", "little by little", "Aprendo poco a poco."),
    ("al principio", "ahl preen-SEE-pyoh", "at the beginning", "Al principio fue dificil."),
    ("al final", "ahl fee-NAHL", "in the end", "Al final todo salio bien."),
    ("por fin", "pohr feen", "finally", "Por fin llegamos!"),
    ("mientras tanto", "MYEHN-trahs TAHN-toh", "meanwhile", "Mientras tanto, espera aqui."),
    ("en seguida", "ehn seh-GEE-dah", "right away", "Vengo en seguida."),
    ("ahora mismo", "ah-OH-rah MEES-moh", "right now", "Lo hago ahora mismo."),
    ("de pronto", "deh PROHN-toh", "suddenly", "De pronto, sono el telefono."),
    ("de todos modos", "deh TOH-dohs MOH-dohs", "anyway", "De todos modos, gracias."),
    ("en serio", "ehn SEH-ryoh", "seriously", "Hablas en serio?"),
    ("tal vez", "tahl behs", "maybe/perhaps", "Tal vez venga manana."),
    ("quizas", "kee-SAHS", "perhaps", "Quizas tengas razon."),
    ("a lo mejor", "ah loh meh-HOHR", "maybe/probably", "A lo mejor llueve hoy."),
    ("sobre todo", "SOH-breh TOH-doh", "especially", "Me gusta, sobre todo el final."),
    ("mas o menos", "mahs oh MEH-nohs", "more or less", "Mas o menos entiendo."),
    ("ni siquiera", "nee see-KYEH-rah", "not even", "Ni siquiera me miro."),
    ("en absoluto", "ehn ahb-soh-LOO-toh", "absolutely not", "En absoluto, no es verdad."),
    ("ya que", "yah keh", "since/given that", "Ya que estas aqui, ayudame."),
    ("puesto que", "PWEHS-toh keh", "since/given that", "Puesto que insistes, acepto."),
    ("siempre y cuando", "SYEHM-preh ee KWAHN-doh", "as long as", "Siempre y cuando me avises."),
    ("con tal de que", "kohn tahl deh keh", "provided that", "Con tal de que llegues a tiempo."),
    ("a menos que", "ah MEH-nohs keh", "unless", "A menos que cambie de opinion."),
    ("en caso de que", "ehn KAH-soh deh keh", "in case", "En caso de que llueva."),
    ("hasta que", "AHS-tah keh", "until", "Espera hasta que llegue."),
    ("antes de que", "AHN-tehs deh keh", "before", "Llamame antes de que salgas."),
    ("despues de que", "dehs-PWEHS deh keh", "after", "Despues de que termine."),
    ("para que", "PAH-rah keh", "so that", "Te lo digo para que sepas."),
    ("a fin de que", "ah feen deh keh", "in order that", "A fin de que entiendas."),
    ("con el fin de", "kohn ehl feen deh", "in order to", "Con el fin de mejorar."),
    ("a causa de", "ah KOW-sah deh", "because of", "A causa de la lluvia."),
    ("debido a", "deh-BEE-doh ah", "due to", "Debido a problemas tecnicos."),
    ("gracias a", "GRAH-syahs ah", "thanks to", "Gracias a ti, lo logre."),

    # ═══════════════════════════════════════════════════════════════════
    # FALSE FRIENDS (Cognates that don't mean what you think)
    # ═══════════════════════════════════════════════════════════════════
    ("embarazada", "ehm-bah-rah-SAH-dah", "pregnant (not embarrassed!)", "Mi hermana esta embarazada."),
    ("exito", "EHK-see-toh", "success (not exit!)", "El proyecto fue un exito."),
    ("sensible", "sehn-SEE-bleh", "sensitive (not sensible!)", "Es una persona muy sensible."),
    ("libreria", "lee-breh-REE-ah", "bookstore (not library!)", "Compre un libro en la libreria."),
    ("recordar", "reh-kohr-DAR", "to remember (not record!)", "Recuerdo ese dia."),
    ("actual", "ahk-TWAHL", "current (not actual!)", "La situacion actual es dificil."),
    ("asistir", "ah-sees-TEER", "to attend (not assist!)", "Asisto a clases de yoga."),
    ("realizar", "reh-ah-lee-SAR", "to accomplish (not realize!)", "Realice mi sueno."),
    ("contestar", "kohn-tehs-TAR", "to answer (not contest!)", "Contesta el telefono."),
    ("pretender", "preh-tehn-DEHR", "to try (not pretend!)", "Pretendo mejorar."),
    ("soportar", "soh-pohr-TAR", "to tolerate (not support!)", "No soporto el ruido."),
    ("molestar", "moh-lehs-TAR", "to bother (not molest!)", "No me molestes ahora."),
    ("introducir", "een-troh-doo-SEER", "to insert (not introduce!)", "Introduce la tarjeta."),
    ("fabrica", "FAH-bree-kah", "factory (not fabric!)", "Trabaja en una fabrica."),
    ("carpeta", "kar-PEH-tah", "folder (not carpet!)", "Pon los papeles en la carpeta."),
    ("campo", "KAHM-poh", "field/countryside (not camp!)", "Vive en el campo."),
    ("casualidad", "kah-swah-lee-DAHD", "coincidence (not casualty!)", "Que casualidad!"),
    ("compromiso", "kohm-proh-MEE-soh", "commitment (not compromise!)", "Es un gran compromiso."),
    ("constipado", "kohns-tee-PAH-doh", "having a cold (not constipated!)", "Estoy constipado."),
    ("decepcion", "deh-sehp-SYOHN", "disappointment (not deception!)", "Fue una gran decepcion."),
    ("delito", "deh-LEE-toh", "crime (not delight!)", "Cometio un delito grave."),
    ("disgusto", "dees-GOOS-toh", "upset/annoyance (not disgust!)", "Me dio un disgusto."),
    ("diversion", "dee-behr-SYOHN", "fun (not diversion!)", "Busco diversion."),
    ("embarazar", "ehm-bah-rah-SAR", "to impregnate (not embarrass!)", "La embarazo sin querer."),
    ("emocionante", "eh-moh-syoh-NAHN-teh", "exciting (not emotional!)", "Fue un partido emocionante."),
    ("equipaje", "eh-kee-PAH-heh", "luggage (not equipment!)", "Perdieron mi equipaje."),
    ("eventual", "eh-behn-TWAHL", "possible (not eventual!)", "Es un resultado eventual."),
    ("largo", "LAR-goh", "long (not large!)", "Es un camino largo."),
    ("lectura", "lehk-TOO-rah", "reading (not lecture!)", "Me gusta la lectura."),
    ("parientes", "pah-RYEHN-tehs", "relatives (not parents!)", "Mis parientes vienen de visita."),
    ("propaganda", "proh-pah-GAHN-dah", "advertising (not propaganda!)", "Hay mucha propaganda en la tele."),
    ("ropa", "RROH-pah", "clothes (not rope!)", "Compre ropa nueva."),
    ("suceso", "soo-SEH-soh", "event (not success!)", "Fue un suceso importante."),
    ("simpatico", "seem-PAH-tee-koh", "nice/likeable (not sympathetic!)", "Es muy simpatico."),
    ("tuna", "TOO-nah", "prickly pear (not tuna fish!)", "Me gusta la tuna."),

    # ═══════════════════════════════════════════════════════════════════
    # SUBJUNCTIVE TRIGGERS
    # ═══════════════════════════════════════════════════════════════════
    ("es importante que", "ehs eem-pohr-TAHN-teh keh", "it's important that", "Es importante que estudies."),
    ("espero que", "ehs-PEH-roh keh", "I hope that", "Espero que todo salga bien."),
    ("ojala", "oh-hah-LAH", "hopefully/I wish", "Ojala puedas venir."),
    ("aunque", "OWN-keh", "although/even if", "Voy aunque llueva."),
    ("dudo que", "DOO-doh keh", "I doubt that", "Dudo que venga."),
    ("no creo que", "noh KREH-oh keh", "I don't think that", "No creo que sea verdad."),
    ("es posible que", "ehs poh-SEE-bleh keh", "it's possible that", "Es posible que llueva."),
    ("es probable que", "ehs proh-BAH-bleh keh", "it's probable that", "Es probable que gane."),
    ("es necesario que", "ehs neh-seh-SAH-ryoh keh", "it's necessary that", "Es necesario que trabajes."),
    ("quiero que", "KYEH-roh keh", "I want that", "Quiero que vengas."),
    ("necesito que", "neh-seh-SEE-toh keh", "I need that", "Necesito que me ayudes."),
    ("te pido que", "teh PEE-doh keh", "I ask you to", "Te pido que me escuches."),
    ("me alegra que", "meh ah-LEH-grah keh", "I'm glad that", "Me alegra que estes aqui."),
    ("siento que", "SYEHN-toh keh", "I'm sorry that", "Siento que te vayas."),
    ("temo que", "TEH-moh keh", "I fear that", "Temo que sea tarde."),
    ("cuando", "KWAHN-doh", "when (future)", "Cuando llegues, llamame."),
    ("en cuanto", "ehn KWAHN-toh", "as soon as", "En cuanto pueda, te aviso."),
    ("tan pronto como", "tahn PROHN-toh KOH-moh", "as soon as", "Tan pronto como termine."),
    ("despues de que", "dehs-PWEHS deh keh", "after", "Despues de que comas."),
    ("antes de que", "AHN-tehs deh keh", "before", "Antes de que te vayas."),
    ("hasta que", "AHS-tah keh", "until", "Espera hasta que vuelva."),
    ("mientras", "MYEHN-trahs", "while", "Mientras estudies, mejoras."),
    ("a menos que", "ah MEH-nohs keh", "unless", "A menos que cambies de idea."),
    ("con tal de que", "kohn tahl deh keh", "provided that", "Con tal de que lo intentes."),
    ("para que", "PAH-rah keh", "so that", "Lo hago para que entiendas."),
    ("sin que", "seen keh", "without", "Salio sin que lo viera."),

    # ═══════════════════════════════════════════════════════════════════
    # TIME EXPRESSIONS
    # ═══════════════════════════════════════════════════════════════════
    ("hace poco", "AH-seh POH-koh", "a little while ago", "Llegue hace poco."),
    ("dentro de poco", "DEHN-troh deh POH-koh", "in a little while", "Llego dentro de poco."),
    ("a la larga", "ah lah LAR-gah", "in the long run", "A la larga, vale la pena."),
    ("de antemano", "deh ahn-teh-MAH-noh", "beforehand", "Gracias de antemano."),
    ("hace mucho", "AH-seh MOO-choh", "a long time ago", "Fue hace mucho tiempo."),
    ("en aquel entonces", "ehn ah-KEHL ehn-TOHN-sehs", "back then", "En aquel entonces, era diferente."),
    ("hoy en dia", "oy ehn DEE-ah", "nowadays", "Hoy en dia es comun."),
    ("ultimamente", "OOL-tee-mah-MEHN-teh", "lately", "Ultimamente trabajo mucho."),
    ("recientemente", "reh-syehn-teh-MEHN-teh", "recently", "Recientemente me mude."),
    ("antiguamente", "ahn-tee-gwah-MEHN-teh", "in the old days", "Antiguamente no habia internet."),
    ("en el futuro", "ehn ehl foo-TOO-roh", "in the future", "En el futuro sera mejor."),
    ("a partir de ahora", "ah par-TEER deh ah-OH-rah", "from now on", "A partir de ahora, cambio."),
    ("de ahora en adelante", "deh ah-OH-rah ehn ah-deh-LAHN-teh", "from now on", "De ahora en adelante, sere puntual."),
    ("a primera hora", "ah pree-MEH-rah OH-rah", "first thing", "Te llamo a primera hora."),
    ("a ultima hora", "ah OOL-tee-mah OH-rah", "at the last minute", "Cancelo a ultima hora."),
    ("cuanto antes", "KWAHN-toh AHN-tehs", "as soon as possible", "Hazlo cuanto antes."),
    ("lo antes posible", "loh AHN-tehs poh-SEE-bleh", "as soon as possible", "Necesito verlo lo antes posible."),
    ("de vez en cuando", "deh behs ehn KWAHN-doh", "from time to time", "Voy de vez en cuando."),
    ("a veces", "ah BEH-sehs", "sometimes", "A veces me olvido."),
    ("siempre", "SYEHM-preh", "always", "Siempre llego temprano."),
    ("nunca", "NOON-kah", "never", "Nunca me rindo."),
    ("jamas", "hah-MAHS", "never (emphatic)", "Jamas lo olvidare."),
    ("ya", "yah", "already/now", "Ya termine."),
    ("todavia", "toh-dah-BEE-ah", "still/yet", "Todavia no llega."),
    ("aun", "ah-OON", "still/even", "Aun no lo se."),

    # ═══════════════════════════════════════════════════════════════════
    # QUESTION WORDS AND PHRASES
    # ═══════════════════════════════════════════════════════════════════
    ("que", "keh", "what/which", "Que quieres comer?"),
    ("quien", "kyehn", "who", "Quien es esa persona?"),
    ("quienes", "KYEH-nehs", "who (plural)", "Quienes vienen a la fiesta?"),
    ("donde", "DOHN-deh", "where", "Donde esta el bano?"),
    ("adonde", "ah-DOHN-deh", "to where", "Adonde vas?"),
    ("de donde", "deh DOHN-deh", "from where", "De donde eres?"),
    ("cuando", "KWAHN-doh", "when", "Cuando es tu cumpleanos?"),
    ("desde cuando", "DEHS-deh KWAHN-doh", "since when", "Desde cuando vives aqui?"),
    ("hasta cuando", "AHS-tah KWAHN-doh", "until when", "Hasta cuando te quedas?"),
    ("por que", "pohr KEH", "why", "Por que no viniste?"),
    ("para que", "PAH-rah keh", "what for", "Para que sirve esto?"),
    ("como", "KOH-moh", "how", "Como estas?"),
    ("cuanto", "KWAHN-toh", "how much", "Cuanto cuesta?"),
    ("cuantos", "KWAHN-tohs", "how many", "Cuantos anos tienes?"),
    ("cual", "kwahl", "which/what", "Cual prefieres?"),
    ("cuales", "KWAH-lehs", "which ones", "Cuales son tuyos?"),

    # ═══════════════════════════════════════════════════════════════════
    # CONNECTING WORDS
    # ═══════════════════════════════════════════════════════════════════
    ("y", "ee", "and", "Pan y mantequilla."),
    ("e", "eh", "and (before i/hi)", "Madre e hija."),
    ("o", "oh", "or", "Te o cafe?"),
    ("u", "oo", "or (before o/ho)", "Siete u ocho."),
    ("pero", "PEH-roh", "but", "Quiero ir, pero no puedo."),
    ("sino", "SEE-noh", "but rather", "No es azul, sino verde."),
    ("aunque", "OWN-keh", "although", "Aunque llueva, voy."),
    ("porque", "POHR-keh", "because", "Lo hago porque quiero."),
    ("ya que", "yah keh", "since", "Ya que insistes, acepto."),
    ("como", "KOH-moh", "since/as", "Como no llamaste, me fui."),
    ("por eso", "pohr EH-soh", "that's why", "Por eso llegue tarde."),
    ("asi que", "ah-SEE keh", "so", "Asi que eso paso."),
    ("entonces", "ehn-TOHN-sehs", "then/so", "Entonces que hacemos?"),
    ("ademas", "ah-deh-MAHS", "besides/moreover", "Ademas, es mas barato."),
    ("tambien", "tahm-BYEHN", "also", "Yo tambien quiero ir."),
    ("tampoco", "tahm-POH-koh", "neither", "Yo tampoco lo se."),
    ("ni", "nee", "nor/not even", "Ni lo intentes."),
    ("ni siquiera", "nee see-KYEH-rah", "not even", "Ni siquiera lo miro."),
    ("sin embargo", "seen ehm-BAR-goh", "however", "Sin embargo, lo intentare."),
    ("no obstante", "noh ohbs-TAHN-teh", "nevertheless", "No obstante, sigo adelante."),
    ("en cambio", "ehn KAHM-byoh", "on the other hand", "El, en cambio, prefiere te."),
    ("por un lado", "pohr oon LAH-doh", "on one hand", "Por un lado, es interesante."),
    ("por otro lado", "pohr OH-troh LAH-doh", "on the other hand", "Por otro lado, es caro."),
    ("es decir", "ehs deh-SEER", "that is to say", "Es decir, no funciona."),
    ("o sea", "oh SEH-ah", "in other words", "O sea, estas de acuerdo?"),
    ("por ejemplo", "pohr eh-HEHM-ploh", "for example", "Por ejemplo, el cafe."),

    # ═══════════════════════════════════════════════════════════════════
    # EVERYDAY PHRASES
    # ═══════════════════════════════════════════════════════════════════
    ("buenos dias", "BWEH-nohs DEE-ahs", "good morning", "Buenos dias, como estas?"),
    ("buenas tardes", "BWEH-nahs TAR-dehs", "good afternoon", "Buenas tardes a todos."),
    ("buenas noches", "BWEH-nahs NOH-chehs", "good evening/night", "Buenas noches, que descanses."),
    ("hola", "OH-lah", "hello", "Hola, que tal?"),
    ("adios", "ah-DYOHS", "goodbye", "Adios, hasta pronto!"),
    ("hasta luego", "AHS-tah LWEH-goh", "see you later", "Hasta luego, nos vemos."),
    ("hasta manana", "AHS-tah mah-NYAH-nah", "see you tomorrow", "Hasta manana en clase."),
    ("hasta pronto", "AHS-tah PROHN-toh", "see you soon", "Hasta pronto, amigo."),
    ("nos vemos", "nohs BEH-mohs", "see you", "Nos vemos el lunes."),
    ("que tal", "keh tahl", "how's it going", "Que tal tu dia?"),
    ("como estas", "KOH-moh ehs-TAHS", "how are you", "Como estas hoy?"),
    ("muy bien", "mwee byehn", "very well", "Estoy muy bien, gracias."),
    ("mas o menos", "mahs oh MEH-nohs", "so-so", "Mas o menos, tirando."),
    ("gracias", "GRAH-syahs", "thank you", "Muchas gracias por todo."),
    ("de nada", "deh NAH-dah", "you're welcome", "De nada, un placer."),
    ("por favor", "pohr fah-BOHR", "please", "Por favor, ayudame."),
    ("lo siento", "loh SYEHN-toh", "I'm sorry", "Lo siento mucho."),
    ("perdon", "pehr-DOHN", "excuse me/sorry", "Perdon, no te vi."),
    ("disculpe", "dees-KOOL-peh", "excuse me (formal)", "Disculpe, donde esta...?"),
    ("con permiso", "kohn pehr-MEE-soh", "excuse me (passing)", "Con permiso, necesito pasar."),
    ("salud", "sah-LOOD", "bless you/cheers", "Salud! Por tu exito."),
    ("felicidades", "feh-lee-see-DAH-dehs", "congratulations", "Felicidades por tu logro!"),
    ("buen provecho", "bwehn proh-BEH-choh", "enjoy your meal", "Buen provecho a todos."),
    ("que aproveche", "keh ah-proh-BEH-cheh", "enjoy your meal", "Que aproveche!"),
    ("que te mejores", "keh teh meh-HOH-rehs", "get well soon", "Que te mejores pronto."),
    ("buena suerte", "BWEH-nah SWEHR-teh", "good luck", "Buena suerte en el examen."),
    ("que te vaya bien", "keh teh BAH-yah byehn", "take care", "Que te vaya bien!"),
    ("cuidate", "kwee-DAH-teh", "take care", "Cuidate mucho."),
    ("igualmente", "ee-gwahl-MEHN-teh", "likewise", "Feliz ano! Igualmente."),
    ("con mucho gusto", "kohn MOO-choh GOOS-toh", "with pleasure", "Con mucho gusto te ayudo."),
    ("encantado", "ehn-kahn-TAH-doh", "pleased to meet you", "Encantado de conocerte."),
    ("mucho gusto", "MOO-choh GOOS-toh", "nice to meet you", "Mucho gusto, soy Ana."),
    ("como te llamas", "KOH-moh teh YAH-mahs", "what's your name", "Como te llamas?"),
    ("de donde eres", "deh DOHN-deh EH-rehs", "where are you from", "De donde eres?"),
    ("a que te dedicas", "ah keh teh deh-DEE-kahs", "what do you do", "A que te dedicas?"),
    ("en que trabajas", "ehn keh trah-BAH-hahs", "what's your job", "En que trabajas?"),
    ("que hora es", "keh OH-rah ehs", "what time is it", "Que hora es?"),
    ("que dia es hoy", "keh DEE-ah ehs oy", "what day is it", "Que dia es hoy?"),
    ("que tiempo hace", "keh TYEHM-poh AH-seh", "what's the weather", "Que tiempo hace hoy?"),
    ("cuanto cuesta", "KWAHN-toh KWEHS-tah", "how much does it cost", "Cuanto cuesta esto?"),
    ("me puede ayudar", "meh PWEH-deh ah-yoo-DAR", "can you help me", "Me puede ayudar?"),
    ("no entiendo", "noh ehn-TYEHN-doh", "I don't understand", "Lo siento, no entiendo."),
    ("puede repetir", "PWEH-deh reh-peh-TEER", "can you repeat", "Puede repetir, por favor?"),
    ("mas despacio", "mahs dehs-PAH-syoh", "more slowly", "Mas despacio, por favor."),
    ("como se dice", "KOH-moh seh DEE-seh", "how do you say", "Como se dice 'hello'?"),
    ("que significa", "keh seeg-nee-FEE-kah", "what does it mean", "Que significa esta palabra?"),
    ("no se", "noh seh", "I don't know", "No se la respuesta."),
    ("creo que si", "KREH-oh keh see", "I think so", "Creo que si."),
    ("creo que no", "KREH-oh keh noh", "I don't think so", "Creo que no."),
    ("claro", "KLAH-roh", "of course/sure", "Claro que si!"),
    ("vale", "BAH-leh", "okay (Spain)", "Vale, nos vemos luego."),
    ("dale", "DAH-leh", "okay (Latin America)", "Dale, hagamoslo."),
    ("esta bien", "ehs-TAH byehn", "it's okay", "Esta bien, no te preocupes."),
    ("no hay problema", "noh ay proh-BLEH-mah", "no problem", "No hay problema."),
    ("no pasa nada", "noh PAH-sah NAH-dah", "it's nothing", "No pasa nada, tranquilo."),
    ("en serio", "ehn SEH-ryoh", "seriously?", "En serio? No lo puedo creer."),
    ("de verdad", "deh behr-DAHD", "really?", "De verdad? Que bien!"),
    ("que bien", "keh byehn", "how nice!", "Que bien que llegaste!"),
    ("que bueno", "keh BWEH-noh", "that's great", "Que bueno que viniste!"),
    ("que lastima", "keh LAHS-tee-mah", "what a pity", "Que lastima que no puedas venir."),
    ("que pena", "keh PEH-nah", "what a shame", "Que pena que paso eso."),
    ("que horror", "keh oh-RROHR", "how awful", "Que horror! Que paso?"),
    ("que rollo", "keh RROH-yoh", "what a drag", "Que rollo tener que esperar."),
    ("que lio", "keh LEE-oh", "what a mess", "Que lio se armo!"),
    ("que barbaridad", "keh bar-bah-ree-DAHD", "how outrageous", "Que barbaridad!"),
    ("no me digas", "noh meh DEE-gahs", "you don't say", "No me digas! En serio?"),
]

# Extended vocabulary with paired example sentences. Each 5-tuple is
# (spanish, pronunciation, english, example1, example2). These get two
# sentences rendered (separated by a newline) in the blocking overlay so the
# learner has more to read than the greyscaled ad in the corner.
SPANISH_VOCABULARY_EXTENDED = [
    # ── FOOD & DRINK ───────────────────────────────────────────────────
    ("desayunar", "deh-sah-yoo-NAR", "to have breakfast",
     "Desayuno huevos todos los dias.", "Nunca desayuno antes de las siete."),
    ("almorzar", "al-mor-SAR", "to have lunch",
     "Almorzamos juntos en la oficina.", "Siempre almuerzo a la una."),
    ("cenar", "seh-NAR", "to have dinner",
     "Cenamos pescado esta noche.", "Prefiero cenar temprano."),
    ("probar", "proh-BAR", "to try/taste",
     "Prueba la sopa, esta deliciosa.", "Nunca he probado el ceviche."),
    ("masticar", "mahs-tee-KAR", "to chew",
     "Mastica despacio para digerir mejor.", "El bebe aun no sabe masticar."),
    ("tragar", "trah-GAR", "to swallow",
     "No puedo tragar esta pastilla.", "Me cuesta tragar cuando estoy nervioso."),
    ("servir", "sehr-BEER", "to serve",
     "Sirveme un vaso de agua, por favor.", "Los meseros sirven con una sonrisa."),
    ("hornear", "or-neh-AR", "to bake",
     "Voy a hornear un pastel de chocolate.", "Hornea el pan por veinte minutos."),
    ("freir", "freh-EER", "to fry",
     "Frie las papas hasta que esten doradas.", "No me gusta freir con mucho aceite."),
    ("hervir", "ehr-BEER", "to boil",
     "Hierve el agua antes de echar la pasta.", "La leche esta a punto de hervir."),
    ("derretir", "deh-rreh-TEER", "to melt",
     "Derrite la mantequilla en la sarten.", "El helado se derrite rapido al sol."),
    ("congelar", "kohn-heh-LAR", "to freeze",
     "Congela las sobras para la semana.", "El lago se congelo anoche."),
    ("sabroso", "sah-BROH-soh", "tasty",
     "Este guiso esta muy sabroso.", "La abuela cocina muy sabroso."),
    ("picante", "pee-KAHN-teh", "spicy",
     "Me encanta la comida picante.", "Esta salsa esta demasiado picante."),
    ("dulce", "DOOL-seh", "sweet",
     "Los mangos estan bien dulces.", "Prefiero el cafe sin dulce."),
    ("amargo", "ah-MAR-goh", "bitter",
     "El cafe sin azucar es muy amargo.", "Esta medicina tiene un sabor amargo."),
    ("salado", "sah-LAH-doh", "salty",
     "La sopa quedo muy salada.", "Me gusta el queso salado."),
    ("acido", "AH-see-doh", "sour/acidic",
     "El limon es muy acido.", "Esta naranja esta un poco acida."),
    ("fresco", "FREHS-koh", "fresh",
     "Compramos pan fresco cada manana.", "El pescado debe estar fresco."),
    ("caducar", "kah-doo-KAR", "to expire",
     "La leche caduca el lunes.", "Revisa la fecha antes de que caduque."),
    # ── NATURE & WEATHER ───────────────────────────────────────────────
    ("amanecer", "ah-mah-neh-SEHR", "sunrise / to dawn",
     "Vimos el amanecer en la playa.", "Amanece muy temprano en verano."),
    ("atardecer", "ah-tar-deh-SEHR", "sunset / to grow late",
     "El atardecer pinto el cielo de rosa.", "Caminamos hasta que atardecio."),
    ("anochecer", "ah-noh-cheh-SEHR", "nightfall",
     "Anochece antes en invierno.", "Volvio a casa al anochecer."),
    ("lluvia", "YOO-byah", "rain",
     "La lluvia no paro en toda la noche.", "Trae paraguas, viene lluvia."),
    ("nieve", "NYEH-beh", "snow",
     "La nieve cubrio las montanas.", "Los ninos juegan en la nieve."),
    ("viento", "BYEHN-toh", "wind",
     "El viento agito las hojas.", "Hay mucho viento esta tarde."),
    ("relampago", "rreh-LAHM-pah-goh", "lightning",
     "Vi un relampago enorme.", "Los relampagos iluminaban el cielo."),
    ("trueno", "TRWEH-noh", "thunder",
     "Un trueno desperto al bebe.", "Los truenos sonaban muy cerca."),
    ("bosque", "BOHS-keh", "forest",
     "Caminamos por el bosque toda la manana.", "El bosque huele a pino."),
    ("arena", "ah-REH-nah", "sand",
     "La arena esta caliente a mediodia.", "Hicimos castillos de arena."),
    ("ola", "OH-lah", "wave",
     "Las olas estan enormes hoy.", "Salto la ola antes de que me tire."),
    ("corriente", "koh-RRYEHN-teh", "current/stream",
     "La corriente del rio es fuerte.", "Cuidado con la corriente del mar."),
    ("pradera", "prah-DEH-rah", "meadow",
     "Nos sentamos en la pradera a leer.", "La pradera esta llena de flores."),
    ("cima", "SEE-mah", "peak/summit",
     "Llegamos a la cima al mediodia.", "La cima estaba cubierta de nieve."),
    ("valle", "BAH-yeh", "valley",
     "El valle se ve precioso desde aqui.", "Un rio cruza todo el valle."),
    ("nublado", "noo-BLAH-doh", "cloudy",
     "El cielo esta nublado hoy.", "Esperaba sol pero amanecio nublado."),
    ("soleado", "soh-leh-AH-doh", "sunny",
     "Fue un dia soleado y calido.", "Prefiero los lugares soleados."),
    ("humedo", "OO-meh-doh", "humid/damp",
     "El clima aqui es muy humedo.", "La ropa sigue humeda."),
    ("arcoiris", "ar-koh-EE-rees", "rainbow",
     "Salio un arcoiris despues de la lluvia.", "El arcoiris tenia colores vivos."),
    ("temblar", "tehm-BLAR", "to tremble/shake",
     "La tierra temblo por unos segundos.", "Tiemblo cuando hace tanto frio."),
    # ── EMOTIONS & FEELINGS ────────────────────────────────────────────
    ("alegria", "ah-leh-GREE-ah", "joy",
     "Senti una alegria inmensa al verte.", "La alegria se contagia."),
    ("tristeza", "trees-TEH-sah", "sadness",
     "Una tristeza profunda lo invadio.", "La tristeza pasa con el tiempo."),
    ("miedo", "MYEH-doh", "fear",
     "Le tengo miedo a las alturas.", "El miedo lo paralizo."),
    ("sorpresa", "sohr-PREH-sah", "surprise",
     "Que sorpresa tan agradable!", "La sorpresa le dejo sin palabras."),
    ("enojo", "eh-NOH-hoh", "anger",
     "Su enojo duro todo el dia.", "No pude esconder mi enojo."),
    ("rabia", "RRAH-byah", "rage/fury",
     "Una rabia enorme lo dominaba.", "Golpeo la mesa con rabia."),
    ("calma", "KAHL-mah", "calm",
     "Respira y busca la calma.", "Despues de la tormenta vino la calma."),
    ("paz", "pahs", "peace",
     "Busco paz y tranquilidad.", "Hay mucha paz en este lugar."),
    ("vergüenza", "behr-GWEHN-sah", "shame/embarrassment",
     "Me da vergüenza hablar en publico.", "Sintio vergüenza por el error."),
    ("orgullo", "or-GOO-yoh", "pride",
     "Lo dijo con mucho orgullo.", "El orgullo no le deja disculparse."),
    ("esperanza", "ehs-peh-RAHN-sah", "hope",
     "Nunca pierdas la esperanza.", "Hay esperanza para todos."),
    ("nostalgia", "nos-TAHL-hyah", "nostalgia",
     "Siento nostalgia por mi pueblo.", "La cancion me da nostalgia."),
    ("emocionado", "eh-moh-syoh-NAH-doh", "excited",
     "Estoy emocionado por el viaje.", "Estaba muy emocionada al recibirlo."),
    ("confundido", "kohn-foon-DEE-doh", "confused",
     "Estoy confundido con las instrucciones.", "Me miro confundido y se fue."),
    ("abrumado", "ah-broo-MAH-doh", "overwhelmed",
     "Se siente abrumado por el trabajo.", "No te sientas abrumado, vamos paso a paso."),
    ("aliviado", "ah-lee-BYAH-doh", "relieved",
     "Me siento aliviado al oirte.", "Se sintio aliviada despues del examen."),
    ("agotado", "ah-goh-TAH-doh", "exhausted",
     "Llegue agotado del trabajo.", "Estoy agotada, necesito dormir."),
    ("tranquilo", "trahn-KEE-loh", "calm/peaceful",
     "Quedate tranquilo, todo va bien.", "Vive en un barrio muy tranquilo."),
    ("nervioso", "nehr-BYOH-soh", "nervous",
     "Estoy nervioso por la entrevista.", "No te pongas nervioso."),
    ("enamorado", "eh-nah-moh-RAH-doh", "in love",
     "Esta enamorado de ella.", "Se nota que estan enamorados."),
    # ── TRAVEL & TRANSPORT ─────────────────────────────────────────────
    ("viajar", "byah-HAR", "to travel",
     "Me gusta viajar en tren.", "Viajamos a Europa el verano pasado."),
    ("equipaje", "eh-kee-PAH-heh", "luggage",
     "Pierdo el equipaje en cada vuelo.", "Lleva poco equipaje."),
    ("maleta", "mah-LEH-tah", "suitcase",
     "No cierra la maleta, esta muy llena.", "Mi maleta se perdio en el vuelo."),
    ("pasaporte", "pah-sah-POR-teh", "passport",
     "Renove mi pasaporte el mes pasado.", "Trae el pasaporte al aeropuerto."),
    ("aduana", "ah-DWAH-nah", "customs",
     "La aduana reviso cada maleta.", "Declaramos todo en la aduana."),
    ("vuelo", "BWEH-loh", "flight",
     "El vuelo sale a las cinco.", "Mi vuelo se retraso dos horas."),
    ("aterrizar", "ah-teh-rree-SAR", "to land",
     "Aterrizamos con una hora de retraso.", "El avion esta por aterrizar."),
    ("despegar", "dehs-peh-GAR", "to take off",
     "El avion despego puntualmente.", "Despegamos a las ocho en punto."),
    ("reservar", "rreh-sehr-BAR", "to book/reserve",
     "Reserve una mesa para dos.", "Reservamos el hotel con meses de anticipacion."),
    ("confirmar", "kohn-feer-MAR", "to confirm",
     "Confirma tu asistencia por favor.", "El hotel confirmo la reservacion."),
    ("retrasar", "rreh-trah-SAR", "to delay",
     "El trafico me retraso media hora.", "Retrasaron el vuelo otra vez."),
    ("cancelar", "kahn-seh-LAR", "to cancel",
     "Tuve que cancelar la cita.", "Cancelaron el vuelo por mal clima."),
    ("embarcar", "ehm-bar-KAR", "to board",
     "Empezamos a embarcar en diez minutos.", "Embarco por la puerta siete."),
    ("conducir", "kohn-doo-SEER", "to drive",
     "Prefiero conducir que ir en tren.", "No me gusta conducir de noche."),
    ("estacionar", "ehs-tah-syoh-NAR", "to park",
     "No encuentro donde estacionar.", "Estaciono cerca de la entrada."),
    ("peaje", "peh-AH-heh", "toll",
     "Hay un peaje a diez kilometros.", "El peaje subio de precio."),
    ("itinerario", "ee-tee-neh-RAH-ryoh", "itinerary",
     "El itinerario incluye tres ciudades.", "Cambiamos el itinerario a ultima hora."),
    ("frontera", "frohn-TEH-rah", "border",
     "Cruzamos la frontera al amanecer.", "La frontera estaba cerrada."),
    ("recorrer", "rreh-koh-RREHR", "to travel through/cover",
     "Recorrimos todo el pais en coche.", "Quiero recorrer America Latina."),
    ("alojamiento", "ah-loh-hah-MYEHN-toh", "lodging/accommodation",
     "El alojamiento incluye desayuno.", "Buscamos alojamiento barato."),
    # ── TECHNOLOGY & DIGITAL ───────────────────────────────────────────
    ("enchufar", "ehn-choo-FAR", "to plug in",
     "Enchufa el cargador a la pared.", "Olvide enchufar la laptop anoche."),
    ("descargar", "dehs-kar-GAR", "to download",
     "Descarga la aplicacion gratis.", "Descargue todos los episodios."),
    ("actualizar", "ak-twah-lee-SAR", "to update",
     "Actualiza el sistema operativo.", "La app se actualizo sola."),
    ("contrasena", "kohn-trah-SEH-nyah", "password",
     "Cambia tu contrasena cada mes.", "Olvide mi contrasena otra vez."),
    ("usuario", "oo-SWAH-ryoh", "user / username",
     "Cada usuario tiene un perfil.", "Ingresa tu nombre de usuario."),
    ("pantalla", "pahn-TAH-yah", "screen",
     "La pantalla se apago sola.", "Limpia la pantalla con un pano suave."),
    ("correo", "koh-RREH-oh", "email / mail",
     "Revisa tu correo, te envie algo.", "Recibi un correo sospechoso."),
    ("mensaje", "mehn-SAH-heh", "message",
     "Te dejo un mensaje en el buzon.", "Me llego un mensaje urgente."),
    ("aplicacion", "ah-plee-kah-SYOHN", "application/app",
     "Instale una nueva aplicacion.", "La aplicacion se cerro sola."),
    ("archivo", "ar-CHEE-boh", "file",
     "Guarda el archivo en la nube.", "El archivo es demasiado grande."),
    ("carpeta", "kar-PEH-tah", "folder",
     "Ordena los archivos en carpetas.", "Creo una carpeta para las fotos."),
    ("respaldo", "rrehs-PAHL-doh", "backup",
     "Haz un respaldo antes de formatear.", "Perdi todo por no tener respaldo."),
    ("cargar", "kar-GAR", "to charge / load",
     "Pon el telefono a cargar.", "La pagina tarda en cargar."),
    ("apagar", "ah-pah-GAR", "to turn off",
     "Apaga la luz antes de salir.", "Apaga el telefono en el cine."),
    ("encender", "ehn-sehn-DEHR", "to turn on",
     "Enciende el ventilador.", "Enciendo la computadora temprano."),
    ("conectar", "koh-nehk-TAR", "to connect",
     "Conecta el cable al router.", "No puedo conectarme al wifi."),
    ("desconectar", "dehs-koh-nehk-TAR", "to disconnect",
     "Desconecta el cargador al salir.", "Me desconecto de internet los fines de semana."),
    ("navegador", "nah-beh-gah-DOHR", "web browser",
     "Prueba en otro navegador.", "El navegador se cerro sin avisar."),
    ("enlace", "ehn-LAH-seh", "link",
     "Haz clic en este enlace.", "El enlace ya no funciona."),
    ("pegar", "peh-GAR", "to paste / stick",
     "Pega el texto en el correo.", "Pego el cartel en la pared."),
    # ── WORK & MONEY ───────────────────────────────────────────────────
    ("trabajar", "trah-bah-HAR", "to work",
     "Trabajo desde casa los viernes.", "Trabajamos en equipo en este proyecto."),
    ("empleo", "ehm-PLEH-oh", "employment / job",
     "Busco un empleo de medio tiempo.", "Perdio su empleo el mes pasado."),
    ("sueldo", "SWEHL-doh", "salary",
     "Mi sueldo subio este ano.", "El sueldo no alcanza para todo."),
    ("gastar", "gahs-TAR", "to spend",
     "Gaste mucho en el viaje.", "No gastes todo en un dia."),
    ("ahorrar", "ah-oh-RRAR", "to save (money)",
     "Ahorro un poco cada mes.", "Ahorramos para comprar una casa."),
    ("prestar", "prehs-TAR", "to lend",
     "Prestame tu paraguas.", "Le preste mi bici a mi hermano."),
    ("pedir prestado", "peh-DEER prehs-TAH-doh", "to borrow",
     "Pedi prestado un libro.", "Nunca pido prestado dinero."),
    ("deber", "deh-BEHR", "to owe / should",
     "Te debo diez pesos.", "Deberias descansar un poco."),
    ("pagar", "pah-GAR", "to pay",
     "Yo pago la cuenta esta vez.", "Paga con tarjeta, es mas facil."),
    ("factura", "fahk-TOO-rah", "invoice / bill",
     "La factura llega a fin de mes.", "Pide la factura al mesero."),
    ("recibo", "rreh-SEE-boh", "receipt",
     "Guarda el recibo por si acaso.", "Pedi el recibo al cajero."),
    ("impuesto", "eem-PWEHS-toh", "tax",
     "Pago impuestos todos los anos.", "El impuesto subio este mes."),
    ("inversion", "een-behr-SYOHN", "investment",
     "Hice una pequena inversion.", "La inversion dio buenos frutos."),
    ("ganancia", "gah-NAHN-syah", "profit / gain",
     "La ganancia fue mejor de lo esperado.", "Reinvirtio toda la ganancia."),
    ("perdida", "PEHR-dee-dah", "loss",
     "Fue una perdida importante.", "La perdida del cliente nos dolio."),
    ("presupuesto", "preh-soo-PWEHS-toh", "budget",
     "Tengo un presupuesto ajustado.", "Pide un presupuesto antes de firmar."),
    ("jefe", "HEH-feh", "boss",
     "Mi jefe es muy justo.", "El jefe pidio otra reunion."),
    ("ascender", "ah-sehn-DEHR", "to promote / go up",
     "La ascendieron el mes pasado.", "Ascender requiere mucho esfuerzo."),
    ("despedir", "dehs-peh-DEER", "to fire / say goodbye",
     "Lo despidieron sin aviso.", "Nos despedimos en el aeropuerto."),
    ("renunciar", "rreh-noon-SYAR", "to quit / resign",
     "Renuncio a su puesto hoy.", "Renunciar no es facil."),
    # ── HEALTH & BODY ──────────────────────────────────────────────────
    ("respirar", "rrehs-pee-RAR", "to breathe",
     "Respira hondo y cuenta hasta diez.", "El aire puro es bueno para respirar."),
    ("descansar", "dehs-kahn-SAR", "to rest",
     "Descansa un rato, lo necesitas.", "Descansamos bajo la sombra."),
    ("estornudar", "ehs-tor-noo-DAR", "to sneeze",
     "El polen me hace estornudar.", "No paro de estornudar."),
    ("toser", "toh-SEHR", "to cough",
     "El nino tose por la noche.", "Me da pena toser en publico."),
    ("sudar", "soo-DAR", "to sweat",
     "Sudo mucho cuando corro.", "El calor hace sudar a todos."),
    ("doler", "doh-LEHR", "to hurt",
     "Me duele la cabeza.", "Le duelen los pies despues de caminar."),
    ("sanar", "sah-NAR", "to heal",
     "La herida sana lentamente.", "El tiempo ayuda a sanar."),
    ("enfermarse", "ehn-fehr-MAR-seh", "to get sick",
     "Me enferme por el cambio de clima.", "Se enferma facilmente en invierno."),
    ("estirar", "ehs-tee-RAR", "to stretch",
     "Estira los brazos antes de correr.", "Estirate bien al levantarte."),
    ("caminar", "kah-mee-NAR", "to walk",
     "Caminamos por el parque cada tarde.", "Caminar ayuda a pensar mejor."),
    ("correr", "koh-RREHR", "to run",
     "Corro tres kilometros por la manana.", "No corras con las tijeras."),
    ("saltar", "sahl-TAR", "to jump",
     "Los ninos saltan en la cama.", "Salte el charco para no mojarme."),
    ("nadar", "nah-DAR", "to swim",
     "Nado en la piscina los sabados.", "Aprendi a nadar a los cinco anos."),
    ("latir", "lah-TEER", "to beat (heart)",
     "Mi corazon late muy rapido.", "Sentia latir el corazon de emocion."),
    ("receta", "rreh-SEH-tah", "prescription / recipe",
     "Necesitas receta para este medicamento.", "Me paso la receta de su abuela."),
    ("medicina", "meh-dee-SEE-nah", "medicine",
     "Toma la medicina con agua.", "La medicina tiene mal sabor."),
    ("cirugia", "see-roo-HEE-ah", "surgery",
     "La cirugia duro tres horas.", "Se recupera bien de la cirugia."),
    ("chequeo", "cheh-KEH-oh", "checkup",
     "Tengo un chequeo anual manana.", "Hazte un chequeo pronto."),
    ("dieta", "DYEH-tah", "diet",
     "Empece una dieta nueva.", "La dieta me dio energia."),
    ("costumbre", "kohs-TOOM-breh", "habit / custom",
     "Tengo la costumbre de leer antes de dormir.", "Es una costumbre familiar."),
    # ── DAILY LIFE & CHORES ────────────────────────────────────────────
    ("limpiar", "leem-PYAR", "to clean",
     "Limpio la cocina despues de cenar.", "Limpiamos juntos los domingos."),
    ("barrer", "bah-RREHR", "to sweep",
     "Barrio la sala esta manana.", "Barrer es la tarea que menos me gusta."),
    ("trapear", "trah-peh-AR", "to mop",
     "Trapeo el piso con vinagre.", "Trapea despues de barrer."),
    ("planchar", "plahn-CHAR", "to iron",
     "Plancho mis camisas los domingos.", "Planchar nunca se acaba."),
    ("tender", "tehn-DEHR", "to hang out (laundry) / tend",
     "Tiendo la ropa al sol.", "Tiende la cama al levantarte."),
    ("doblar", "doh-BLAR", "to fold / turn",
     "Doblo la ropa recien seca.", "Dobla a la derecha en la esquina."),
    ("regar", "rreh-GAR", "to water",
     "Riega las plantas cada dos dias.", "Olvide regar el jardin."),
    ("ordenar", "or-deh-NAR", "to tidy / order",
     "Ordena tu cuarto antes de salir.", "Ordenamos los libros por tamano."),
    ("apretar", "ah-preh-TAR", "to press / tighten",
     "Aprieta el boton rojo.", "Aprieta bien los tornillos."),
    ("arrancar", "ah-rrahn-KAR", "to start (engine) / pull off",
     "El coche no arranca.", "Arrancamos a las seis de la manana."),
    ("reparar", "rreh-pah-RAR", "to repair",
     "Voy a reparar la lavadora yo mismo.", "Repararon la calle por fin."),
    ("averia", "ah-beh-REE-ah", "breakdown / malfunction",
     "Tuvimos una averia en el camino.", "El coche quedo con una averia."),
    ("reciclar", "rreh-see-KLAR", "to recycle",
     "Reciclamos papel y plastico.", "Reciclar es una buena costumbre."),
    ("botar", "boh-TAR", "to throw out",
     "Bota la basura antes de salir.", "No botes eso, se puede reusar."),
    ("recoger", "rreh-koh-HEHR", "to pick up / gather",
     "Recojo a los ninos a las tres.", "Recogimos manzanas del arbol."),
    ("guardar", "gwar-DAR", "to put away / keep",
     "Guarda los platos en el mueble.", "Guardo recuerdos de esa epoca."),
    ("colgar", "kohl-GAR", "to hang / hang up",
     "Cuelga el abrigo en el perchero.", "No cuelgues el telefono."),
    ("enchufe", "ehn-CHOO-feh", "outlet / plug",
     "Hay un enchufe detras del sofa.", "Este enchufe no funciona."),
    ("bombilla", "bohm-BEE-yah", "light bulb",
     "Se fundio la bombilla del bano.", "Cambiamos a bombillas led."),
    ("grifo", "GREE-foh", "faucet / tap",
     "El grifo gotea toda la noche.", "Cierra bien el grifo."),
    # ── FAMILY & SOCIAL ────────────────────────────────────────────────
    ("primo", "PREE-moh", "cousin",
     "Mi primo vive en Madrid.", "Tengo primos en todo el pais."),
    ("sobrino", "soh-BREE-noh", "nephew",
     "Mi sobrino cumple cinco anos.", "Visito a mis sobrinos cada sabado."),
    ("cuñado", "koo-NYAH-doh", "brother-in-law",
     "Mi cuñado es muy gracioso.", "Fuimos al partido con el cuñado."),
    ("suegra", "SWEH-grah", "mother-in-law",
     "Mi suegra cocina delicioso.", "Hablo con mi suegra los domingos."),
    ("pareja", "pah-REH-hah", "partner / couple",
     "Vamos a cenar con la pareja.", "Son pareja desde la universidad."),
    ("vecino", "beh-SEE-noh", "neighbor",
     "Los vecinos son muy amables.", "Saludo a la vecina cada manana."),
    ("invitado", "een-bee-TAH-doh", "guest",
     "Tenemos invitados esta noche.", "Los invitados llegaron puntuales."),
    ("anfitrion", "ahn-fee-TRYOHN", "host",
     "Fue un anfitrion excelente.", "Los anfitriones nos recibieron con cafe."),
    ("amistad", "ah-mees-TAHD", "friendship",
     "La amistad verdadera es rara.", "Nuestra amistad vale mucho."),
    ("compañero", "kohm-pah-NYEH-roh", "companion / coworker",
     "Mi compañero de oficina se jubila.", "Fuimos compañeros de clase."),
    ("extraño", "ehks-TRAH-nyoh", "stranger / strange",
     "No hables con extraños.", "Que extraño que no llame."),
    ("reunirse", "rreh-oo-NEER-seh", "to meet / gather",
     "Nos reunimos los viernes.", "Se reunieron para planear el viaje."),
    ("celebrar", "seh-leh-BRAR", "to celebrate",
     "Celebramos su cumpleanos.", "Celebremos este logro."),
    ("felicitar", "feh-lee-see-TAR", "to congratulate",
     "Te felicito por el ascenso.", "Todos lo felicitaron."),
    ("regalar", "rreh-gah-LAR", "to gift",
     "Le regalamos un libro.", "Regala tiempo a quien amas."),
    ("comprometerse", "kohm-proh-meh-TEHR-seh", "to commit / get engaged",
     "Se comprometieron en la playa.", "Me comprometo a terminar el proyecto."),
    ("confiar", "kohn-FYAR", "to trust",
     "Confio en ti plenamente.", "Es dificil confiar despues de eso."),
    ("mentir", "mehn-TEER", "to lie",
     "No me mientas, te conozco.", "Mintio para no preocuparnos."),
    ("disculparse", "dees-kool-PAR-seh", "to apologize",
     "Me disculpe con ella ayer.", "Disculpate antes de que sea tarde."),
    ("perdonar", "pehr-doh-NAR", "to forgive",
     "Perdona mis errores.", "Perdono pero no olvido."),
    # ── LEARNING & THINKING ────────────────────────────────────────────
    ("aprender", "ah-prehn-DEHR", "to learn",
     "Aprendo espanol cada dia.", "Aprendimos mucho en ese viaje."),
    ("ensenar", "ehn-seh-NYAR", "to teach",
     "Mi madre me ensena a cocinar.", "Ensenar requiere paciencia."),
    ("estudiar", "ehs-too-DYAR", "to study",
     "Estudio por las noches.", "Estudiamos juntos para el examen."),
    ("repasar", "rreh-pah-SAR", "to review",
     "Repaso los apuntes antes de dormir.", "Repasamos la leccion anterior."),
    ("memorizar", "meh-moh-ree-SAR", "to memorize",
     "Memorice todos los verbos.", "Es dificil memorizar tanto."),
    ("entender", "ehn-tehn-DEHR", "to understand",
     "No entiendo esta oracion.", "Entiendo perfectamente tu punto."),
    ("explicar", "ehks-plee-KAR", "to explain",
     "Explicame como funciona.", "El profesor explico muy bien."),
    ("preguntar", "preh-goon-TAR", "to ask",
     "Pregunta si tienes dudas.", "Le pregunte la hora."),
    ("responder", "rrehs-pohn-DEHR", "to answer / respond",
     "Respondio a todas las preguntas.", "Responde cuando puedas."),
    ("dudar", "doo-DAR", "to doubt",
     "Dudo que pueda venir manana.", "No dudes en llamarme."),
    ("razon", "rrah-SOHN", "reason",
     "Tienes razon, me equivoque.", "No hay razon para enojarse."),
    ("opinion", "oh-pee-NYOHN", "opinion",
     "Respeto tu opinion.", "Tu opinion me importa."),
    ("argumentar", "ar-goo-mehn-TAR", "to argue (a point)",
     "Argumenta bien sus ideas.", "Argumentamos por horas sobre el tema."),
    ("proponer", "proh-poh-NEHR", "to propose",
     "Propongo un brindis.", "Proponemos cambiar el plan."),
    ("resolver", "rreh-sohl-BEHR", "to solve",
     "Resolvi el problema sola.", "Vamos a resolver esto juntos."),
    ("analizar", "ah-nah-lee-SAR", "to analyze",
     "Analizamos el reporte ayer.", "Analiza bien antes de decidir."),
    ("comparar", "kohm-pah-RAR", "to compare",
     "Compara los dos precios.", "No compares manzanas con peras."),
    ("recordar", "rreh-kor-DAR", "to remember",
     "Recuerdo ese dia claramente.", "Recuerdame comprar leche."),
    ("olvidar", "ohl-bee-DAR", "to forget",
     "Olvide mis llaves en casa.", "No olvides apagar la luz."),
    ("imaginar", "ee-mah-hee-NAR", "to imagine",
     "Imagina como seria vivir alli.", "No te imaginas lo contenta que estoy."),
    # ── SUBJUNCTIVE / ADVANCED PATTERNS ────────────────────────────────
    ("ojala que", "oh-hah-LAH keh", "I hope that",
     "Ojala que llegue a tiempo.", "Ojala que todo salga bien."),
    ("aunque", "AWN-keh", "although / even though",
     "Aunque llueva, iremos.", "Aunque tenga tiempo, no lo hare."),
    ("por si acaso", "por see ah-KAH-soh", "just in case",
     "Lleva un abrigo por si acaso.", "Guardo el recibo por si acaso."),
    ("en cuanto", "ehn KWAHN-toh", "as soon as",
     "Llamame en cuanto llegues.", "En cuanto termine, salgo."),
    ("a menos que", "ah MEH-nohs keh", "unless",
     "No salgo a menos que pare la lluvia.", "Te lo presto a menos que lo necesites."),
    ("con tal de que", "kohn tahl deh keh", "provided that",
     "Voy, con tal de que tu vengas.", "Firma, con tal de que leas primero."),
    ("antes de que", "AHN-tehs deh keh", "before (subj)",
     "Termina antes de que oscurezca.", "Llamame antes de que salgas."),
    ("despues de que", "dehs-PWEHS deh keh", "after (subj)",
     "Te llamo despues de que comamos.", "Hablamos despues de que acabes."),
    ("para que", "PAH-rah keh", "so that",
     "Te lo explico para que entiendas.", "Lo repito para que lo memorices."),
    ("sin que", "seen keh", "without (subj)",
     "Salio sin que nadie lo viera.", "Lo hizo sin que le pidieran."),
    ("a que", "ah keh", "I bet / to (go) to",
     "A que no sabes quien llamo.", "Voy a que me corten el pelo."),
    ("como si", "KOH-moh see", "as if",
     "Habla como si supiera todo.", "Actuaba como si nada hubiera pasado."),
    ("por mas que", "por mahs keh", "no matter how much",
     "Por mas que lo intente, no entiende.", "Por mas que llueva, iremos."),
    ("valer la pena", "bah-LEHR lah PEH-nah", "to be worth it",
     "El viaje valio la pena.", "Vale la pena esperar un poco."),
    ("dar igual", "dar ee-GWAHL", "to be the same / not matter",
     "Me da igual la hora.", "Le dio igual la respuesta."),
    ("echar de menos", "eh-CHAR deh MEH-nohs", "to miss someone",
     "Echo de menos a mi familia.", "Echamos de menos ese sabor."),
    ("hacer falta", "ah-SEHR FAHL-tah", "to be lacking / needed",
     "Hace falta sal en la sopa.", "Me hace falta un descanso."),
    ("tener ganas", "teh-NEHR GAH-nahs", "to feel like",
     "Tengo ganas de viajar.", "No tenia ganas de salir."),
    ("poner de acuerdo", "poh-NEHR deh ah-KWEHR-doh", "to agree",
     "No nos ponemos de acuerdo.", "Se pusieron de acuerdo en el precio."),
    ("salirse con la suya", "sah-LEER-seh kohn lah SOO-yah", "to get one's way",
     "Siempre se sale con la suya.", "No te saldras con la suya esta vez."),
]

# Unified accessor used by the blocking overlay — callers can iterate both
# 4-tuples and 5-tuples. The extra list triples our dual-sentence coverage
# without losing the original beginner/intermediate pool.
VOCABULARY_COMBINED = SPANISH_VOCABULARY + SPANISH_VOCABULARY_EXTENDED
