"""
Spanish vocabulary for ad blocking overlays.

Contains beginner and intermediate level Spanish words and phrases
displayed during ad blocks to help users practice Spanish.

Format: (spanish, pronunciation, english, example_sentence)
Pronunciation uses simplified phonetics: capitals indicate stressed syllables
"""

# Spanish vocabulary - beginner and intermediate level
SPANISH_VOCABULARY = [
    # ═══════════════════════════════════════════════════════════════════
    # COMMON VERBS (Beginner)
    # ═══════════════════════════════════════════════════════════════════
    ("hablar", "ah-BLAR", "to speak", "Hablo espanol todos los dias."),
    ("comer", "koh-MEHR", "to eat", "Vamos a comer tacos."),
    ("vivir", "bee-BEER", "to live", "Vivo en una ciudad grande."),
    ("ser", "sehr", "to be (permanent)", "Soy de Mexico."),
    ("estar", "ehs-TAR", "to be (temporary)", "Estoy cansado hoy."),
    ("tener", "teh-NEHR", "to have", "Tengo dos hermanos."),
    ("hacer", "ah-SEHR", "to do/make", "Hago la tarea cada noche."),
    ("ir", "eer", "to go", "Voy al supermercado."),
    ("poder", "poh-DEHR", "to be able to/can", "Puedo ayudarte manana."),
    ("querer", "keh-REHR", "to want/love", "Quiero aprender mas."),
    ("saber", "sah-BEHR", "to know (facts)", "Se la respuesta."),
    ("conocer", "koh-noh-SEHR", "to know (people/places)", "Conozco a tu hermana."),
    ("decir", "deh-SEER", "to say/tell", "Dime la verdad."),
    ("venir", "beh-NEER", "to come", "Ven a mi casa."),
    ("salir", "sah-LEER", "to leave/go out", "Salgo a las ocho."),
    ("llegar", "yeh-GAR", "to arrive", "Llego tarde al trabajo."),
    ("poner", "poh-NEHR", "to put/place", "Pon los libros en la mesa."),
    ("dar", "dar", "to give", "Te doy un regalo."),
    ("ver", "behr", "to see", "Veo una pelicula."),
    ("pensar", "pehn-SAR", "to think", "Pienso en ti."),
    ("creer", "kreh-EHR", "to believe", "Creo que tienes razon."),
    ("encontrar", "ehn-kohn-TRAR", "to find", "Encontre mis llaves."),
    ("seguir", "seh-GEER", "to follow/continue", "Sigue todo recto."),
    ("llamar", "yah-MAR", "to call", "Te llamo manana."),
    ("sentir", "sehn-TEER", "to feel", "Siento mucho frio."),
    ("dejar", "deh-HAR", "to leave/let", "Deja la puerta abierta."),
    ("parecer", "pah-reh-SEHR", "to seem", "Parece interesante."),
    ("quedar", "keh-DAR", "to stay/remain", "Me quedo en casa."),
    ("pasar", "pah-SAR", "to pass/happen", "Que paso ayer?"),
    ("esperar", "ehs-peh-RAR", "to wait/hope", "Espero tu respuesta."),
    ("buscar", "boos-KAR", "to look for", "Busco un restaurante."),
    ("entrar", "ehn-TRAR", "to enter", "Entra por la puerta principal."),
    ("trabajar", "trah-bah-HAR", "to work", "Trabajo desde casa."),
    ("necesitar", "neh-seh-see-TAR", "to need", "Necesito tu ayuda."),
    ("llevar", "yeh-BAR", "to carry/wear", "Llevo una camisa azul."),
    ("empezar", "ehm-peh-SAR", "to begin", "Empiezo a las nueve."),
    ("terminar", "tehr-mee-NAR", "to finish", "Termine el proyecto."),
    ("abrir", "ah-BREER", "to open", "Abre la ventana."),
    ("cerrar", "seh-RAR", "to close", "Cierra la puerta."),
    ("escribir", "ehs-kree-BEER", "to write", "Escribo un correo."),
    ("leer", "leh-EHR", "to read", "Leo un libro cada mes."),
    ("dormir", "dohr-MEER", "to sleep", "Duermo ocho horas."),
    ("correr", "koh-REHR", "to run", "Corro en el parque."),
    ("caminar", "kah-mee-NAR", "to walk", "Camino al trabajo."),
    ("comprar", "kohm-PRAR", "to buy", "Compro frutas frescas."),
    ("vender", "behn-DEHR", "to sell", "Vendo mi carro viejo."),
    ("pagar", "pah-GAR", "to pay", "Pago con tarjeta."),
    ("preguntar", "preh-goon-TAR", "to ask", "Pregunto por direcciones."),
    ("responder", "rehs-pohn-DEHR", "to answer", "Respondo rapidamente."),
    ("ayudar", "ah-yoo-DAR", "to help", "Te ayudo con eso."),

    # ═══════════════════════════════════════════════════════════════════
    # COMMON VERBS (Intermediate)
    # ═══════════════════════════════════════════════════════════════════
    ("aprovechar", "ah-proh-beh-CHAR", "to take advantage of", "Hay que aprovechar el tiempo."),
    ("lograr", "loh-GRAR", "to achieve/manage", "Logre terminar el proyecto."),
    ("desarrollar", "deh-sah-roh-YAR", "to develop", "Vamos a desarrollar una app."),
    ("destacar", "dehs-tah-KAR", "to stand out", "Su trabajo destaca por su calidad."),
    ("enfrentar", "ehn-frehn-TAR", "to face/confront", "Debemos enfrentar los problemas."),
    ("realizar", "reh-ah-lee-SAR", "to carry out/accomplish", "Voy a realizar mi sueno."),
    ("averiguar", "ah-beh-ree-GWAR", "to find out", "Necesito averiguar la verdad."),
    ("pertenecer", "pehr-teh-neh-SEHR", "to belong", "Este libro pertenece a Maria."),
    ("alcanzar", "ahl-kahn-SAR", "to reach/achieve", "Quiero alcanzar mis metas."),
    ("surgir", "soor-HEER", "to arise/emerge", "Surgio un problema inesperado."),
    ("tardar", "tar-DAR", "to take time/be late", "Cuanto tardas en llegar?"),
    ("soler", "soh-LEHR", "to usually do", "Suelo desayunar temprano."),
    ("proponer", "proh-poh-NEHR", "to propose", "Propongo una solucion."),
    ("suponer", "soo-poh-NEHR", "to suppose", "Supongo que tienes razon."),
    ("mantener", "mahn-teh-NEHR", "to maintain", "Mantiene una actitud positiva."),
    ("obtener", "ohb-teh-NEHR", "to obtain", "Obtuve buenos resultados."),
    ("reconocer", "reh-koh-noh-SEHR", "to recognize", "Reconozco mi error."),
    ("producir", "proh-doo-SEER", "to produce", "Producimos mucho cafe."),
    ("reducir", "reh-doo-SEER", "to reduce", "Debemos reducir los gastos."),
    ("conducir", "kohn-doo-SEER", "to drive", "Conduzco con cuidado."),
    ("traducir", "trah-doo-SEER", "to translate", "Traduzco documentos."),
    ("elegir", "eh-leh-HEER", "to choose", "Elige tu favorito."),
    ("exigir", "ehk-see-HEER", "to demand", "Exijo una explicacion."),
    ("dirigir", "dee-ree-HEER", "to direct/lead", "Dirijo el proyecto."),
    ("influir", "een-floo-EER", "to influence", "Influye en mi decision."),
    ("contribuir", "kohn-tree-boo-EER", "to contribute", "Contribuyo al equipo."),
    ("construir", "kohns-troo-EER", "to build", "Construyen un edificio nuevo."),
    ("destruir", "dehs-troo-EER", "to destroy", "No destruyas el medio ambiente."),
    ("incluir", "een-kloo-EER", "to include", "Incluye todos los detalles."),
    ("concluir", "kohn-kloo-EER", "to conclude", "Concluyo mi presentacion."),
    ("huir", "oo-EER", "to flee", "Huyen del peligro."),
    ("advertir", "ahd-behr-TEER", "to warn", "Te advierto del riesgo."),
    ("convertir", "kohn-behr-TEER", "to convert", "Convierto dolares a euros."),
    ("invertir", "een-behr-TEER", "to invest", "Invierto en mi educacion."),
    ("divertir", "dee-behr-TEER", "to amuse", "Me divierto con amigos."),
    ("preferir", "preh-feh-REER", "to prefer", "Prefiero el cafe."),
    ("sugerir", "soo-heh-REER", "to suggest", "Sugiero una alternativa."),
    ("mentir", "mehn-TEER", "to lie", "Nunca miento."),
    ("medir", "meh-DEER", "to measure", "Mido la distancia."),
    ("pedir", "peh-DEER", "to ask for/order", "Pido la cuenta."),
    ("repetir", "reh-peh-TEER", "to repeat", "Repite la pregunta."),
    ("competir", "kohm-peh-TEER", "to compete", "Competimos en el torneo."),
    ("servir", "sehr-BEER", "to serve", "Sirvo la cena."),
    ("vestir", "behs-TEER", "to dress", "Me visto rapidamente."),
    ("conseguir", "kohn-seh-GEER", "to get/obtain", "Consegui el trabajo."),
    ("perseguir", "pehr-seh-GEER", "to pursue/chase", "Persigo mis suenos."),
    ("despedir", "dehs-peh-DEER", "to fire/say goodbye", "Me despido de ti."),
    ("impedir", "eem-peh-DEER", "to prevent", "Impido el acceso."),
    ("corregir", "koh-reh-HEER", "to correct", "Corrijo los errores."),
    ("recoger", "reh-koh-HEHR", "to pick up/collect", "Recojo a los ninos."),
    ("proteger", "proh-teh-HEHR", "to protect", "Protejo a mi familia."),
    ("escoger", "ehs-koh-HEHR", "to choose", "Escoge el mejor."),
    ("coger", "koh-HEHR", "to take/catch", "Cojo el autobus."),
    ("valer", "bah-LEHR", "to be worth", "Vale la pena intentar."),
    ("caber", "kah-BEHR", "to fit", "No cabe en la maleta."),
    ("caer", "kah-EHR", "to fall", "Me cai en la calle."),
    ("traer", "trah-EHR", "to bring", "Traigo buenas noticias."),
    ("ofrecer", "oh-freh-SEHR", "to offer", "Ofrezco mi ayuda."),
    ("aparecer", "ah-pah-reh-SEHR", "to appear", "Aparece en la pantalla."),
    ("desaparecer", "deh-sah-pah-reh-SEHR", "to disappear", "Desaparece sin explicacion."),
    ("crecer", "kreh-SEHR", "to grow", "Las plantas crecen rapido."),
    ("agradecer", "ah-grah-deh-SEHR", "to thank", "Agradezco tu ayuda."),
    ("establecer", "ehs-tah-bleh-SEHR", "to establish", "Establezco nuevas metas."),
    ("pertenecer", "pehr-teh-neh-SEHR", "to belong", "Pertenezco a este grupo."),
    ("merecer", "meh-reh-SEHR", "to deserve", "Mereces lo mejor."),
    ("nacer", "nah-SEHR", "to be born", "Naci en primavera."),
    ("obedecer", "oh-beh-deh-SEHR", "to obey", "Obedece las reglas."),

    # ═══════════════════════════════════════════════════════════════════
    # REFLEXIVE VERBS
    # ═══════════════════════════════════════════════════════════════════
    ("levantarse", "leh-bahn-TAR-seh", "to get up", "Me levanto a las siete."),
    ("acostarse", "ah-kohs-TAR-seh", "to go to bed", "Me acuesto temprano."),
    ("despertarse", "dehs-pehr-TAR-seh", "to wake up", "Me despierto con alarma."),
    ("ducharse", "doo-CHAR-seh", "to shower", "Me ducho por la manana."),
    ("banarse", "bah-NYAR-seh", "to bathe", "Me bano en la noche."),
    ("vestirse", "behs-TEER-seh", "to get dressed", "Me visto rapidamente."),
    ("peinarse", "peh-ee-NAR-seh", "to comb one's hair", "Me peino antes de salir."),
    ("lavarse", "lah-BAR-seh", "to wash oneself", "Me lavo las manos."),
    ("cepillarse", "seh-pee-YAR-seh", "to brush", "Me cepillo los dientes."),
    ("maquillarse", "mah-kee-YAR-seh", "to put on makeup", "Me maquillo poco."),
    ("afeitarse", "ah-feh-ee-TAR-seh", "to shave", "Me afeito cada dia."),
    ("sentarse", "sehn-TAR-seh", "to sit down", "Me siento en el sofa."),
    ("quedarse", "keh-DAR-seh", "to stay", "Me quedo en casa hoy."),
    ("irse", "EER-seh", "to leave/go away", "Me voy a las cinco."),
    ("llamarse", "yah-MAR-seh", "to be called", "Me llamo Carlos."),
    ("sentirse", "sehn-TEER-seh", "to feel", "Me siento feliz."),
    ("ponerse", "poh-NEHR-seh", "to put on/become", "Me pongo nervioso."),
    ("quitarse", "kee-TAR-seh", "to take off", "Me quito los zapatos."),
    ("casarse", "kah-SAR-seh", "to get married", "Se casan en junio."),
    ("divorciarse", "dee-bohr-see-AR-seh", "to get divorced", "Se divorciaron el ano pasado."),
    ("mudarse", "moo-DAR-seh", "to move (house)", "Me mudo a otra ciudad."),
    ("quejarse", "keh-HAR-seh", "to complain", "Se queja de todo."),
    ("olvidarse", "ohl-bee-DAR-seh", "to forget", "Me olvide de la cita."),
    ("acordarse", "ah-kohr-DAR-seh", "to remember", "Me acuerdo de ti."),
    ("comprometerse", "kohm-proh-meh-TEHR-seh", "to commit oneself", "Me comprometo a estudiar."),
    ("enterarse", "ehn-teh-RAR-seh", "to find out", "Me entere de la noticia."),
    ("darse cuenta", "DAR-seh KWEHN-tah", "to realize", "Me di cuenta del error."),
    ("equivocarse", "eh-kee-boh-KAR-seh", "to be wrong/make mistake", "Todos nos equivocamos."),
    ("preocuparse", "preh-oh-koo-PAR-seh", "to worry", "No te preocupes por eso."),
    ("arrepentirse", "ah-reh-pehn-TEER-seh", "to regret", "Me arrepiento de esa decision."),
    ("atreverse", "ah-treh-BEHR-seh", "to dare", "Me atrevo a intentarlo."),
    ("quemarse", "keh-MAR-seh", "to burn oneself", "Me queme con el cafe."),
    ("cortarse", "kohr-TAR-seh", "to cut oneself", "Me corte el dedo."),
    ("caerse", "kah-EHR-seh", "to fall down", "Me cai en la escalera."),
    ("romperse", "rohm-PEHR-seh", "to break", "Se rompio el vaso."),
    ("perderse", "pehr-DEHR-seh", "to get lost", "Me perdi en la ciudad."),
    ("aburrirse", "ah-boo-REER-seh", "to get bored", "Me aburro facilmente."),
    ("divertirse", "dee-behr-TEER-seh", "to have fun", "Me divierto mucho."),
    ("enojarse", "eh-noh-HAR-seh", "to get angry", "Me enojo rapidamente."),
    ("calmarse", "kahl-MAR-seh", "to calm down", "Calmate, por favor."),
    ("relajarse", "reh-lah-HAR-seh", "to relax", "Me relajo los fines de semana."),
    ("concentrarse", "kohn-sehn-TRAR-seh", "to concentrate", "Me concentro en el trabajo."),
    ("dedicarse", "deh-dee-KAR-seh", "to dedicate oneself", "Me dedico a la musica."),
    ("acercarse", "ah-sehr-KAR-seh", "to approach", "Me acerco a la puerta."),
    ("alejarse", "ah-leh-HAR-seh", "to move away", "Me alejo del ruido."),

    # ═══════════════════════════════════════════════════════════════════
    # ADJECTIVES (Beginner)
    # ═══════════════════════════════════════════════════════════════════
    ("grande", "GRAHN-deh", "big/large", "Es una casa grande."),
    ("pequeno", "peh-KEH-nyoh", "small", "Tengo un perro pequeno."),
    ("bueno", "BWEH-noh", "good", "Es un buen libro."),
    ("malo", "MAH-loh", "bad", "Hace mal tiempo hoy."),
    ("nuevo", "NWEH-boh", "new", "Compre un carro nuevo."),
    ("viejo", "bee-EH-hoh", "old", "Mi abuelo es viejo."),
    ("joven", "HOH-behn", "young", "Es una mujer joven."),
    ("alto", "AHL-toh", "tall/high", "El edificio es muy alto."),
    ("bajo", "BAH-hoh", "short/low", "El precio esta bajo."),
    ("largo", "LAR-goh", "long", "Es un camino largo."),
    ("corto", "KOHR-toh", "short", "Fue una pelicula corta."),
    ("ancho", "AHN-choh", "wide", "El rio es muy ancho."),
    ("estrecho", "ehs-TREH-choh", "narrow", "La calle es estrecha."),
    ("gordo", "GOHR-doh", "fat", "El gato esta gordo."),
    ("delgado", "dehl-GAH-doh", "thin", "Es muy delgado."),
    ("fuerte", "FWEHR-teh", "strong", "Es un hombre fuerte."),
    ("debil", "DEH-beel", "weak", "Me siento debil hoy."),
    ("rapido", "RAH-pee-doh", "fast", "El tren es muy rapido."),
    ("lento", "LEHN-toh", "slow", "El trafico esta lento."),
    ("facil", "FAH-seel", "easy", "El examen fue facil."),
    ("dificil", "dee-FEE-seel", "difficult", "Es un problema dificil."),
    ("rico", "REE-koh", "rich/delicious", "La comida esta rica."),
    ("pobre", "POH-breh", "poor", "Es una familia pobre."),
    ("caro", "KAH-roh", "expensive", "El hotel es muy caro."),
    ("barato", "bah-RAH-toh", "cheap", "Encontre algo barato."),
    ("limpio", "LEEM-pyoh", "clean", "La casa esta limpia."),
    ("sucio", "SOO-syoh", "dirty", "El piso esta sucio."),
    ("caliente", "kah-LYEHN-teh", "hot", "El cafe esta caliente."),
    ("frio", "FREE-oh", "cold", "El agua esta fria."),
    ("dulce", "DOOL-seh", "sweet", "El pastel es muy dulce."),
    ("salado", "sah-LAH-doh", "salty", "La sopa esta salada."),
    ("amargo", "ah-MAR-goh", "bitter", "El cafe es amargo."),
    ("picante", "pee-KAHN-teh", "spicy", "Me gusta la comida picante."),
    ("feliz", "feh-LEES", "happy", "Estoy muy feliz."),
    ("triste", "TREES-teh", "sad", "Se siente triste hoy."),
    ("cansado", "kahn-SAH-doh", "tired", "Estoy muy cansado."),
    ("enfermo", "ehn-FEHR-moh", "sick", "Mi hijo esta enfermo."),
    ("sano", "SAH-noh", "healthy", "Es importante estar sano."),
    ("ocupado", "oh-koo-PAH-doh", "busy", "Estoy muy ocupado."),
    ("libre", "LEE-breh", "free", "Estas libre manana?"),
    ("lleno", "YEH-noh", "full", "El restaurante esta lleno."),
    ("vacio", "bah-SEE-oh", "empty", "El vaso esta vacio."),
    ("abierto", "ah-BYEHR-toh", "open", "La tienda esta abierta."),
    ("cerrado", "seh-RAH-doh", "closed", "El banco esta cerrado."),
    ("correcto", "koh-REHK-toh", "correct", "Tu respuesta es correcta."),
    ("incorrecto", "een-koh-REHK-toh", "incorrect", "Eso es incorrecto."),
    ("seguro", "seh-GOO-roh", "safe/sure", "Estoy seguro de eso."),
    ("peligroso", "peh-lee-GROH-soh", "dangerous", "Es un lugar peligroso."),
    ("importante", "eem-pohr-TAHN-teh", "important", "Es muy importante."),
    ("interesante", "een-teh-reh-SAHN-teh", "interesting", "El libro es interesante."),

    # ═══════════════════════════════════════════════════════════════════
    # ADJECTIVES (Intermediate)
    # ═══════════════════════════════════════════════════════════════════
    ("disponible", "dees-poh-NEE-bleh", "available", "El doctor esta disponible manana."),
    ("imprescindible", "eem-prehs-seen-DEE-bleh", "essential/indispensable", "El agua es imprescindible."),
    ("agotado", "ah-goh-TAH-doh", "exhausted/sold out", "Estoy agotado despues del trabajo."),
    ("capaz", "kah-PAHS", "capable", "Eres capaz de hacerlo."),
    ("dispuesto", "dees-PWEHS-toh", "willing/ready", "Estoy dispuesto a ayudar."),
    ("actual", "ahk-TWAHL", "current (not actual!)", "La situacion actual es dificil."),
    ("adecuado", "ah-deh-KWAH-doh", "adequate/suitable", "Es el momento adecuado."),
    ("amplio", "AHM-plyoh", "wide/spacious", "Tiene un amplio conocimiento."),
    ("complicado", "kohm-plee-KAH-doh", "complicated", "Es un tema complicado."),
    ("sencillo", "sehn-SEE-yoh", "simple", "La solucion es sencilla."),
    ("profundo", "proh-FOON-doh", "deep", "Es un pensamiento profundo."),
    ("superficial", "soo-pehr-fee-SYAHL", "superficial", "Fue un analisis superficial."),
    ("valioso", "bah-LYOH-soh", "valuable", "Es un objeto muy valioso."),
    ("util", "OO-teel", "useful", "Es una herramienta util."),
    ("inutil", "ee-NOO-teel", "useless", "Es completamente inutil."),
    ("obvio", "OHB-byoh", "obvious", "Es algo obvio."),
    ("curioso", "koo-RYOH-soh", "curious", "Soy muy curioso."),
    ("gracioso", "grah-SYOH-soh", "funny", "Es muy gracioso."),
    ("serio", "SEH-ryoh", "serious", "Es un asunto serio."),
    ("tranquilo", "trahn-KEE-loh", "calm/quiet", "El lugar es muy tranquilo."),
    ("ruidoso", "rrwee-DOH-soh", "noisy", "La calle es ruidosa."),
    ("orgulloso", "ohr-goo-YOH-soh", "proud", "Estoy orgulloso de ti."),
    ("avergonzado", "ah-behr-gohn-SAH-doh", "embarrassed", "Estoy avergonzado."),
    ("emocionado", "eh-moh-syoh-NAH-doh", "excited", "Estoy emocionado por el viaje."),
    ("preocupado", "preh-oh-koo-PAH-doh", "worried", "Estoy preocupado por el examen."),
    ("sorprendido", "sohr-prehn-DEE-doh", "surprised", "Estoy muy sorprendido."),
    ("confundido", "kohn-foon-DEE-doh", "confused", "Estoy confundido."),
    ("decepcionado", "deh-sehp-syoh-NAH-doh", "disappointed", "Estoy decepcionado."),
    ("asustado", "ah-soos-TAH-doh", "scared", "El nino esta asustado."),
    ("celoso", "seh-LOH-soh", "jealous", "Es una persona celosa."),
    ("terco", "TEHR-koh", "stubborn", "Es muy terco."),
    ("timido", "TEE-mee-doh", "shy", "Mi hijo es timido."),
    ("amable", "ah-MAH-bleh", "kind", "Es una persona amable."),
    ("grosero", "groh-SEH-roh", "rude", "No seas grosero."),
    ("educado", "eh-doo-KAH-doh", "polite", "Es muy educado."),
    ("honesto", "oh-NEHS-toh", "honest", "Es una persona honesta."),
    ("sincero", "seen-SEH-roh", "sincere", "Fue un comentario sincero."),
    ("leal", "leh-AHL", "loyal", "Es un amigo leal."),
    ("fiel", "fyehl", "faithful", "Es un perro fiel."),
    ("generoso", "heh-neh-ROH-soh", "generous", "Es muy generoso."),
    ("tacano", "tah-KAH-nyoh", "stingy", "No seas tacano."),
    ("perezoso", "peh-reh-SOH-soh", "lazy", "Soy un poco perezoso."),
    ("trabajador", "trah-bah-hah-DOHR", "hardworking", "Es muy trabajador."),
    ("inteligente", "een-teh-lee-HEHN-teh", "intelligent", "Es muy inteligente."),
    ("listo", "LEES-toh", "smart/ready", "Estas listo para salir?"),
    ("tonto", "TOHN-toh", "silly/stupid", "No seas tonto."),
    ("sabio", "SAH-byoh", "wise", "Mi abuelo es muy sabio."),
    ("culpable", "kool-PAH-bleh", "guilty", "Se siente culpable."),
    ("inocente", "ee-noh-SEHN-teh", "innocent", "Es inocente."),

    # ═══════════════════════════════════════════════════════════════════
    # NOUNS (Common)
    # ═══════════════════════════════════════════════════════════════════
    ("desarrollo", "deh-sah-RROH-yoh", "development", "El desarrollo del proyecto va bien."),
    ("comportamiento", "kohm-pohr-tah-MYEHN-toh", "behavior", "Su comportamiento es extrano."),
    ("conocimiento", "koh-noh-see-MYEHN-toh", "knowledge", "El conocimiento es poder."),
    ("ambiente", "ahm-BYEHN-teh", "environment/atmosphere", "El ambiente es muy agradable."),
    ("herramienta", "eh-rrah-MYEHN-tah", "tool", "Necesito una herramienta."),
    ("recurso", "reh-KOOR-soh", "resource", "Tenemos pocos recursos."),
    ("prueba", "PRWEH-bah", "test/proof", "Necesito una prueba."),
    ("meta", "MEH-tah", "goal", "Mi meta es aprender espanol."),
    ("reto", "RREH-toh", "challenge", "Es un gran reto personal."),
    ("exito", "EHK-see-toh", "success", "El proyecto fue un exito."),
    ("fracaso", "frah-KAH-soh", "failure", "Aprende de tus fracasos."),
    ("ventaja", "behn-TAH-hah", "advantage", "Tenemos una gran ventaja."),
    ("desventaja", "dehs-behn-TAH-hah", "disadvantage", "Es una desventaja clara."),
    ("oportunidad", "oh-pohr-too-nee-DAHD", "opportunity", "Es una buena oportunidad."),
    ("posibilidad", "poh-see-bee-lee-DAHD", "possibility", "Existe esa posibilidad."),
    ("capacidad", "kah-pah-see-DAHD", "capacity/ability", "Tiene mucha capacidad."),
    ("habilidad", "ah-bee-lee-DAHD", "skill/ability", "Es una habilidad importante."),
    ("costumbre", "kohs-TOOM-breh", "custom/habit", "Es una vieja costumbre."),
    ("tradicion", "trah-dee-SYOHN", "tradition", "Es una tradicion familiar."),
    ("cultura", "kool-TOO-rah", "culture", "Me interesa la cultura mexicana."),
    ("historia", "ees-TOH-ryah", "history/story", "Cuenta una historia interesante."),
    ("cuenta", "KWEHN-tah", "account/bill", "Pago la cuenta, por favor."),
    ("cuento", "KWEHN-toh", "story/tale", "Leo un cuento a mis hijos."),
    ("noticia", "noh-TEE-syah", "news", "Es una buena noticia."),
    ("novedad", "noh-beh-DAHD", "novelty/news", "Que novedades hay?"),
    ("asunto", "ah-SOON-toh", "matter/issue", "Es un asunto importante."),
    ("tema", "TEH-mah", "topic/theme", "Cambiemos de tema."),
    ("problema", "proh-BLEH-mah", "problem", "Tengo un problema."),
    ("solucion", "soh-loo-SYOHN", "solution", "Busco una solucion."),
    ("respuesta", "rrehs-PWEHS-tah", "answer", "Necesito una respuesta."),
    ("pregunta", "preh-GOON-tah", "question", "Tengo una pregunta."),
    ("duda", "DOO-dah", "doubt", "No tengo ninguna duda."),
    ("error", "eh-RROHR", "error/mistake", "Cometio un error grave."),
    ("falta", "FAHL-tah", "lack/fault", "Es mi falta."),
    ("culpa", "KOOL-pah", "blame/fault", "No es tu culpa."),
    ("razon", "rrah-SOHN", "reason", "Tienes toda la razon."),
    ("motivo", "moh-TEE-boh", "motive/reason", "Cual es el motivo?"),
    ("causa", "KOW-sah", "cause", "Es la causa del problema."),
    ("efecto", "eh-FEHK-toh", "effect", "Tiene un efecto positivo."),
    ("resultado", "reh-sool-TAH-doh", "result", "El resultado fue bueno."),
    ("cambio", "KAHM-byoh", "change", "Necesito un cambio."),
    ("mejora", "meh-HOH-rah", "improvement", "Se nota la mejora."),
    ("aumento", "ow-MEHN-toh", "increase", "Hubo un aumento de precios."),
    ("disminucion", "dees-mee-noo-SYOHN", "decrease", "Hay una disminucion notable."),
    ("crecimiento", "kreh-see-MYEHN-toh", "growth", "El crecimiento es rapido."),
    ("nivel", "nee-BEHL", "level", "Subio de nivel."),
    ("grado", "GRAH-doh", "degree/grade", "Tiene un alto grado de dificultad."),
    ("medida", "meh-DEE-dah", "measure", "Tomo medidas urgentes."),
    ("paso", "PAH-soh", "step", "Es un paso importante."),
    ("etapa", "eh-TAH-pah", "stage/phase", "Es la primera etapa."),

    # ═══════════════════════════════════════════════════════════════════
    # EXPRESSIONS AND PHRASES
    # ═══════════════════════════════════════════════════════════════════
    ("sin embargo", "seen ehm-BAR-goh", "however/nevertheless", "Es dificil, sin embargo posible."),
    ("a pesar de", "ah peh-SAR deh", "despite/in spite of", "A pesar de todo, sigo adelante."),
    ("de repente", "deh reh-PEHN-teh", "suddenly", "De repente, empezo a llover."),
    ("hoy en dia", "oy ehn DEE-ah", "nowadays", "Hoy en dia todo es digital."),
    ("cada vez mas", "KAH-dah behs mahs", "more and more", "Es cada vez mas dificil."),
    ("hace poco", "AH-seh POH-koh", "a little while ago", "Llegue hace poco."),
    ("a la larga", "ah lah LAR-gah", "in the long run", "A la larga, vale la pena."),
    ("de antemano", "deh ahn-teh-MAH-noh", "beforehand", "Gracias de antemano."),
    ("en cuanto a", "ehn KWAHN-toh ah", "as for/regarding", "En cuanto a eso, no se."),
    ("por lo tanto", "pohr loh TAHN-toh", "therefore", "Por lo tanto, debemos actuar."),
    ("por lo menos", "pohr loh MEH-nohs", "at least", "Por lo menos lo intentaste."),
    ("por supuesto", "pohr soo-PWEHS-toh", "of course", "Por supuesto que si."),
    ("desde luego", "DEHS-deh LWEH-goh", "of course", "Desde luego que puedo."),
    ("en realidad", "ehn reh-ah-lee-DAHD", "actually/in reality", "En realidad, no es asi."),
    ("de hecho", "deh EH-choh", "in fact", "De hecho, tengo razon."),
    ("en cambio", "ehn KAHM-byoh", "on the other hand", "En cambio, el prefiere cafe."),
    ("en vez de", "ehn behs deh", "instead of", "En vez de quejarme, actuare."),
    ("a menudo", "ah meh-NOO-doh", "often", "Voy a menudo al cine."),
    ("de vez en cuando", "deh behs ehn KWAHN-doh", "from time to time", "Como pizza de vez en cuando."),
    ("poco a poco", "POH-koh ah POH-koh", "little by little", "Aprendo poco a poco."),
    ("al principio", "ahl preen-SEE-pyoh", "at the beginning", "Al principio fue dificil."),
    ("al final", "ahl fee-NAHL", "in the end", "Al final todo salio bien."),
    ("por fin", "pohr feen", "finally", "Por fin llegamos!"),
    ("mientras tanto", "MYEHN-trahs TAHN-toh", "meanwhile", "Mientras tanto, espera aqui."),
    ("en seguida", "ehn seh-GEE-dah", "right away", "Vengo en seguida."),
    ("ahora mismo", "ah-OH-rah MEES-moh", "right now", "Lo hago ahora mismo."),
    ("de pronto", "deh PROHN-toh", "suddenly", "De pronto, sono el telefono."),
    ("de todos modos", "deh TOH-dohs MOH-dohs", "anyway", "De todos modos, gracias."),
    ("en serio", "ehn SEH-ryoh", "seriously", "Hablas en serio?"),
    ("tal vez", "tahl behs", "maybe/perhaps", "Tal vez venga manana."),
    ("quizas", "kee-SAHS", "perhaps", "Quizas tengas razon."),
    ("a lo mejor", "ah loh meh-HOHR", "maybe/probably", "A lo mejor llueve hoy."),
    ("sobre todo", "SOH-breh TOH-doh", "especially", "Me gusta, sobre todo el final."),
    ("mas o menos", "mahs oh MEH-nohs", "more or less", "Mas o menos entiendo."),
    ("ni siquiera", "nee see-KYEH-rah", "not even", "Ni siquiera me miro."),
    ("en absoluto", "ehn ahb-soh-LOO-toh", "absolutely not", "En absoluto, no es verdad."),
    ("ya que", "yah keh", "since/given that", "Ya que estas aqui, ayudame."),
    ("puesto que", "PWEHS-toh keh", "since/given that", "Puesto que insistes, acepto."),
    ("siempre y cuando", "SYEHM-preh ee KWAHN-doh", "as long as", "Siempre y cuando me avises."),
    ("con tal de que", "kohn tahl deh keh", "provided that", "Con tal de que llegues a tiempo."),
    ("a menos que", "ah MEH-nohs keh", "unless", "A menos que cambie de opinion."),
    ("en caso de que", "ehn KAH-soh deh keh", "in case", "En caso de que llueva."),
    ("hasta que", "AHS-tah keh", "until", "Espera hasta que llegue."),
    ("antes de que", "AHN-tehs deh keh", "before", "Llamame antes de que salgas."),
    ("despues de que", "dehs-PWEHS deh keh", "after", "Despues de que termine."),
    ("para que", "PAH-rah keh", "so that", "Te lo digo para que sepas."),
    ("a fin de que", "ah feen deh keh", "in order that", "A fin de que entiendas."),
    ("con el fin de", "kohn ehl feen deh", "in order to", "Con el fin de mejorar."),
    ("a causa de", "ah KOW-sah deh", "because of", "A causa de la lluvia."),
    ("debido a", "deh-BEE-doh ah", "due to", "Debido a problemas tecnicos."),
    ("gracias a", "GRAH-syahs ah", "thanks to", "Gracias a ti, lo logre."),

    # ═══════════════════════════════════════════════════════════════════
    # FALSE FRIENDS (Cognates that don't mean what you think)
    # ═══════════════════════════════════════════════════════════════════
    ("embarazada", "ehm-bah-rah-SAH-dah", "pregnant (not embarrassed!)", "Mi hermana esta embarazada."),
    ("exito", "EHK-see-toh", "success (not exit!)", "El proyecto fue un exito."),
    ("sensible", "sehn-SEE-bleh", "sensitive (not sensible!)", "Es una persona muy sensible."),
    ("libreria", "lee-breh-REE-ah", "bookstore (not library!)", "Compre un libro en la libreria."),
    ("recordar", "reh-kohr-DAR", "to remember (not record!)", "Recuerdo ese dia."),
    ("actual", "ahk-TWAHL", "current (not actual!)", "La situacion actual es dificil."),
    ("asistir", "ah-sees-TEER", "to attend (not assist!)", "Asisto a clases de yoga."),
    ("realizar", "reh-ah-lee-SAR", "to accomplish (not realize!)", "Realice mi sueno."),
    ("contestar", "kohn-tehs-TAR", "to answer (not contest!)", "Contesta el telefono."),
    ("pretender", "preh-tehn-DEHR", "to try (not pretend!)", "Pretendo mejorar."),
    ("soportar", "soh-pohr-TAR", "to tolerate (not support!)", "No soporto el ruido."),
    ("molestar", "moh-lehs-TAR", "to bother (not molest!)", "No me molestes ahora."),
    ("introducir", "een-troh-doo-SEER", "to insert (not introduce!)", "Introduce la tarjeta."),
    ("fabrica", "FAH-bree-kah", "factory (not fabric!)", "Trabaja en una fabrica."),
    ("carpeta", "kar-PEH-tah", "folder (not carpet!)", "Pon los papeles en la carpeta."),
    ("campo", "KAHM-poh", "field/countryside (not camp!)", "Vive en el campo."),
    ("casualidad", "kah-swah-lee-DAHD", "coincidence (not casualty!)", "Que casualidad!"),
    ("compromiso", "kohm-proh-MEE-soh", "commitment (not compromise!)", "Es un gran compromiso."),
    ("constipado", "kohns-tee-PAH-doh", "having a cold (not constipated!)", "Estoy constipado."),
    ("decepcion", "deh-sehp-SYOHN", "disappointment (not deception!)", "Fue una gran decepcion."),
    ("delito", "deh-LEE-toh", "crime (not delight!)", "Cometio un delito grave."),
    ("disgusto", "dees-GOOS-toh", "upset/annoyance (not disgust!)", "Me dio un disgusto."),
    ("diversion", "dee-behr-SYOHN", "fun (not diversion!)", "Busco diversion."),
    ("embarazar", "ehm-bah-rah-SAR", "to impregnate (not embarrass!)", "La embarazo sin querer."),
    ("emocionante", "eh-moh-syoh-NAHN-teh", "exciting (not emotional!)", "Fue un partido emocionante."),
    ("equipaje", "eh-kee-PAH-heh", "luggage (not equipment!)", "Perdieron mi equipaje."),
    ("eventual", "eh-behn-TWAHL", "possible (not eventual!)", "Es un resultado eventual."),
    ("largo", "LAR-goh", "long (not large!)", "Es un camino largo."),
    ("lectura", "lehk-TOO-rah", "reading (not lecture!)", "Me gusta la lectura."),
    ("parientes", "pah-RYEHN-tehs", "relatives (not parents!)", "Mis parientes vienen de visita."),
    ("propaganda", "proh-pah-GAHN-dah", "advertising (not propaganda!)", "Hay mucha propaganda en la tele."),
    ("ropa", "RROH-pah", "clothes (not rope!)", "Compre ropa nueva."),
    ("suceso", "soo-SEH-soh", "event (not success!)", "Fue un suceso importante."),
    ("simpatico", "seem-PAH-tee-koh", "nice/likeable (not sympathetic!)", "Es muy simpatico."),
    ("tuna", "TOO-nah", "prickly pear (not tuna fish!)", "Me gusta la tuna."),

    # ═══════════════════════════════════════════════════════════════════
    # SUBJUNCTIVE TRIGGERS
    # ═══════════════════════════════════════════════════════════════════
    ("es importante que", "ehs eem-pohr-TAHN-teh keh", "it's important that", "Es importante que estudies."),
    ("espero que", "ehs-PEH-roh keh", "I hope that", "Espero que todo salga bien."),
    ("ojala", "oh-hah-LAH", "hopefully/I wish", "Ojala puedas venir."),
    ("aunque", "OWN-keh", "although/even if", "Voy aunque llueva."),
    ("dudo que", "DOO-doh keh", "I doubt that", "Dudo que venga."),
    ("no creo que", "noh KREH-oh keh", "I don't think that", "No creo que sea verdad."),
    ("es posible que", "ehs poh-SEE-bleh keh", "it's possible that", "Es posible que llueva."),
    ("es probable que", "ehs proh-BAH-bleh keh", "it's probable that", "Es probable que gane."),
    ("es necesario que", "ehs neh-seh-SAH-ryoh keh", "it's necessary that", "Es necesario que trabajes."),
    ("quiero que", "KYEH-roh keh", "I want that", "Quiero que vengas."),
    ("necesito que", "neh-seh-SEE-toh keh", "I need that", "Necesito que me ayudes."),
    ("te pido que", "teh PEE-doh keh", "I ask you to", "Te pido que me escuches."),
    ("me alegra que", "meh ah-LEH-grah keh", "I'm glad that", "Me alegra que estes aqui."),
    ("siento que", "SYEHN-toh keh", "I'm sorry that", "Siento que te vayas."),
    ("temo que", "TEH-moh keh", "I fear that", "Temo que sea tarde."),
    ("cuando", "KWAHN-doh", "when (future)", "Cuando llegues, llamame."),
    ("en cuanto", "ehn KWAHN-toh", "as soon as", "En cuanto pueda, te aviso."),
    ("tan pronto como", "tahn PROHN-toh KOH-moh", "as soon as", "Tan pronto como termine."),
    ("despues de que", "dehs-PWEHS deh keh", "after", "Despues de que comas."),
    ("antes de que", "AHN-tehs deh keh", "before", "Antes de que te vayas."),
    ("hasta que", "AHS-tah keh", "until", "Espera hasta que vuelva."),
    ("mientras", "MYEHN-trahs", "while", "Mientras estudies, mejoras."),
    ("a menos que", "ah MEH-nohs keh", "unless", "A menos que cambies de idea."),
    ("con tal de que", "kohn tahl deh keh", "provided that", "Con tal de que lo intentes."),
    ("para que", "PAH-rah keh", "so that", "Lo hago para que entiendas."),
    ("sin que", "seen keh", "without", "Salio sin que lo viera."),

    # ═══════════════════════════════════════════════════════════════════
    # TIME EXPRESSIONS
    # ═══════════════════════════════════════════════════════════════════
    ("hace poco", "AH-seh POH-koh", "a little while ago", "Llegue hace poco."),
    ("dentro de poco", "DEHN-troh deh POH-koh", "in a little while", "Llego dentro de poco."),
    ("a la larga", "ah lah LAR-gah", "in the long run", "A la larga, vale la pena."),
    ("de antemano", "deh ahn-teh-MAH-noh", "beforehand", "Gracias de antemano."),
    ("hace mucho", "AH-seh MOO-choh", "a long time ago", "Fue hace mucho tiempo."),
    ("en aquel entonces", "ehn ah-KEHL ehn-TOHN-sehs", "back then", "En aquel entonces, era diferente."),
    ("hoy en dia", "oy ehn DEE-ah", "nowadays", "Hoy en dia es comun."),
    ("ultimamente", "OOL-tee-mah-MEHN-teh", "lately", "Ultimamente trabajo mucho."),
    ("recientemente", "reh-syehn-teh-MEHN-teh", "recently", "Recientemente me mude."),
    ("antiguamente", "ahn-tee-gwah-MEHN-teh", "in the old days", "Antiguamente no habia internet."),
    ("en el futuro", "ehn ehl foo-TOO-roh", "in the future", "En el futuro sera mejor."),
    ("a partir de ahora", "ah par-TEER deh ah-OH-rah", "from now on", "A partir de ahora, cambio."),
    ("de ahora en adelante", "deh ah-OH-rah ehn ah-deh-LAHN-teh", "from now on", "De ahora en adelante, sere puntual."),
    ("a primera hora", "ah pree-MEH-rah OH-rah", "first thing", "Te llamo a primera hora."),
    ("a ultima hora", "ah OOL-tee-mah OH-rah", "at the last minute", "Cancelo a ultima hora."),
    ("cuanto antes", "KWAHN-toh AHN-tehs", "as soon as possible", "Hazlo cuanto antes."),
    ("lo antes posible", "loh AHN-tehs poh-SEE-bleh", "as soon as possible", "Necesito verlo lo antes posible."),
    ("de vez en cuando", "deh behs ehn KWAHN-doh", "from time to time", "Voy de vez en cuando."),
    ("a veces", "ah BEH-sehs", "sometimes", "A veces me olvido."),
    ("siempre", "SYEHM-preh", "always", "Siempre llego temprano."),
    ("nunca", "NOON-kah", "never", "Nunca me rindo."),
    ("jamas", "hah-MAHS", "never (emphatic)", "Jamas lo olvidare."),
    ("ya", "yah", "already/now", "Ya termine."),
    ("todavia", "toh-dah-BEE-ah", "still/yet", "Todavia no llega."),
    ("aun", "ah-OON", "still/even", "Aun no lo se."),

    # ═══════════════════════════════════════════════════════════════════
    # QUESTION WORDS AND PHRASES
    # ═══════════════════════════════════════════════════════════════════
    ("que", "keh", "what/which", "Que quieres comer?"),
    ("quien", "kyehn", "who", "Quien es esa persona?"),
    ("quienes", "KYEH-nehs", "who (plural)", "Quienes vienen a la fiesta?"),
    ("donde", "DOHN-deh", "where", "Donde esta el bano?"),
    ("adonde", "ah-DOHN-deh", "to where", "Adonde vas?"),
    ("de donde", "deh DOHN-deh", "from where", "De donde eres?"),
    ("cuando", "KWAHN-doh", "when", "Cuando es tu cumpleanos?"),
    ("desde cuando", "DEHS-deh KWAHN-doh", "since when", "Desde cuando vives aqui?"),
    ("hasta cuando", "AHS-tah KWAHN-doh", "until when", "Hasta cuando te quedas?"),
    ("por que", "pohr KEH", "why", "Por que no viniste?"),
    ("para que", "PAH-rah keh", "what for", "Para que sirve esto?"),
    ("como", "KOH-moh", "how", "Como estas?"),
    ("cuanto", "KWAHN-toh", "how much", "Cuanto cuesta?"),
    ("cuantos", "KWAHN-tohs", "how many", "Cuantos anos tienes?"),
    ("cual", "kwahl", "which/what", "Cual prefieres?"),
    ("cuales", "KWAH-lehs", "which ones", "Cuales son tuyos?"),

    # ═══════════════════════════════════════════════════════════════════
    # CONNECTING WORDS
    # ═══════════════════════════════════════════════════════════════════
    ("y", "ee", "and", "Pan y mantequilla."),
    ("e", "eh", "and (before i/hi)", "Madre e hija."),
    ("o", "oh", "or", "Te o cafe?"),
    ("u", "oo", "or (before o/ho)", "Siete u ocho."),
    ("pero", "PEH-roh", "but", "Quiero ir, pero no puedo."),
    ("sino", "SEE-noh", "but rather", "No es azul, sino verde."),
    ("aunque", "OWN-keh", "although", "Aunque llueva, voy."),
    ("porque", "POHR-keh", "because", "Lo hago porque quiero."),
    ("ya que", "yah keh", "since", "Ya que insistes, acepto."),
    ("como", "KOH-moh", "since/as", "Como no llamaste, me fui."),
    ("por eso", "pohr EH-soh", "that's why", "Por eso llegue tarde."),
    ("asi que", "ah-SEE keh", "so", "Asi que eso paso."),
    ("entonces", "ehn-TOHN-sehs", "then/so", "Entonces que hacemos?"),
    ("ademas", "ah-deh-MAHS", "besides/moreover", "Ademas, es mas barato."),
    ("tambien", "tahm-BYEHN", "also", "Yo tambien quiero ir."),
    ("tampoco", "tahm-POH-koh", "neither", "Yo tampoco lo se."),
    ("ni", "nee", "nor/not even", "Ni lo intentes."),
    ("ni siquiera", "nee see-KYEH-rah", "not even", "Ni siquiera lo miro."),
    ("sin embargo", "seen ehm-BAR-goh", "however", "Sin embargo, lo intentare."),
    ("no obstante", "noh ohbs-TAHN-teh", "nevertheless", "No obstante, sigo adelante."),
    ("en cambio", "ehn KAHM-byoh", "on the other hand", "El, en cambio, prefiere te."),
    ("por un lado", "pohr oon LAH-doh", "on one hand", "Por un lado, es interesante."),
    ("por otro lado", "pohr OH-troh LAH-doh", "on the other hand", "Por otro lado, es caro."),
    ("es decir", "ehs deh-SEER", "that is to say", "Es decir, no funciona."),
    ("o sea", "oh SEH-ah", "in other words", "O sea, estas de acuerdo?"),
    ("por ejemplo", "pohr eh-HEHM-ploh", "for example", "Por ejemplo, el cafe."),

    # ═══════════════════════════════════════════════════════════════════
    # EVERYDAY PHRASES
    # ═══════════════════════════════════════════════════════════════════
    ("buenos dias", "BWEH-nohs DEE-ahs", "good morning", "Buenos dias, como estas?"),
    ("buenas tardes", "BWEH-nahs TAR-dehs", "good afternoon", "Buenas tardes a todos."),
    ("buenas noches", "BWEH-nahs NOH-chehs", "good evening/night", "Buenas noches, que descanses."),
    ("hola", "OH-lah", "hello", "Hola, que tal?"),
    ("adios", "ah-DYOHS", "goodbye", "Adios, hasta pronto!"),
    ("hasta luego", "AHS-tah LWEH-goh", "see you later", "Hasta luego, nos vemos."),
    ("hasta manana", "AHS-tah mah-NYAH-nah", "see you tomorrow", "Hasta manana en clase."),
    ("hasta pronto", "AHS-tah PROHN-toh", "see you soon", "Hasta pronto, amigo."),
    ("nos vemos", "nohs BEH-mohs", "see you", "Nos vemos el lunes."),
    ("que tal", "keh tahl", "how's it going", "Que tal tu dia?"),
    ("como estas", "KOH-moh ehs-TAHS", "how are you", "Como estas hoy?"),
    ("muy bien", "mwee byehn", "very well", "Estoy muy bien, gracias."),
    ("mas o menos", "mahs oh MEH-nohs", "so-so", "Mas o menos, tirando."),
    ("gracias", "GRAH-syahs", "thank you", "Muchas gracias por todo."),
    ("de nada", "deh NAH-dah", "you're welcome", "De nada, un placer."),
    ("por favor", "pohr fah-BOHR", "please", "Por favor, ayudame."),
    ("lo siento", "loh SYEHN-toh", "I'm sorry", "Lo siento mucho."),
    ("perdon", "pehr-DOHN", "excuse me/sorry", "Perdon, no te vi."),
    ("disculpe", "dees-KOOL-peh", "excuse me (formal)", "Disculpe, donde esta...?"),
    ("con permiso", "kohn pehr-MEE-soh", "excuse me (passing)", "Con permiso, necesito pasar."),
    ("salud", "sah-LOOD", "bless you/cheers", "Salud! Por tu exito."),
    ("felicidades", "feh-lee-see-DAH-dehs", "congratulations", "Felicidades por tu logro!"),
    ("buen provecho", "bwehn proh-BEH-choh", "enjoy your meal", "Buen provecho a todos."),
    ("que aproveche", "keh ah-proh-BEH-cheh", "enjoy your meal", "Que aproveche!"),
    ("que te mejores", "keh teh meh-HOH-rehs", "get well soon", "Que te mejores pronto."),
    ("buena suerte", "BWEH-nah SWEHR-teh", "good luck", "Buena suerte en el examen."),
    ("que te vaya bien", "keh teh BAH-yah byehn", "take care", "Que te vaya bien!"),
    ("cuidate", "kwee-DAH-teh", "take care", "Cuidate mucho."),
    ("igualmente", "ee-gwahl-MEHN-teh", "likewise", "Feliz ano! Igualmente."),
    ("con mucho gusto", "kohn MOO-choh GOOS-toh", "with pleasure", "Con mucho gusto te ayudo."),
    ("encantado", "ehn-kahn-TAH-doh", "pleased to meet you", "Encantado de conocerte."),
    ("mucho gusto", "MOO-choh GOOS-toh", "nice to meet you", "Mucho gusto, soy Ana."),
    ("como te llamas", "KOH-moh teh YAH-mahs", "what's your name", "Como te llamas?"),
    ("de donde eres", "deh DOHN-deh EH-rehs", "where are you from", "De donde eres?"),
    ("a que te dedicas", "ah keh teh deh-DEE-kahs", "what do you do", "A que te dedicas?"),
    ("en que trabajas", "ehn keh trah-BAH-hahs", "what's your job", "En que trabajas?"),
    ("que hora es", "keh OH-rah ehs", "what time is it", "Que hora es?"),
    ("que dia es hoy", "keh DEE-ah ehs oy", "what day is it", "Que dia es hoy?"),
    ("que tiempo hace", "keh TYEHM-poh AH-seh", "what's the weather", "Que tiempo hace hoy?"),
    ("cuanto cuesta", "KWAHN-toh KWEHS-tah", "how much does it cost", "Cuanto cuesta esto?"),
    ("me puede ayudar", "meh PWEH-deh ah-yoo-DAR", "can you help me", "Me puede ayudar?"),
    ("no entiendo", "noh ehn-TYEHN-doh", "I don't understand", "Lo siento, no entiendo."),
    ("puede repetir", "PWEH-deh reh-peh-TEER", "can you repeat", "Puede repetir, por favor?"),
    ("mas despacio", "mahs dehs-PAH-syoh", "more slowly", "Mas despacio, por favor."),
    ("como se dice", "KOH-moh seh DEE-seh", "how do you say", "Como se dice 'hello'?"),
    ("que significa", "keh seeg-nee-FEE-kah", "what does it mean", "Que significa esta palabra?"),
    ("no se", "noh seh", "I don't know", "No se la respuesta."),
    ("creo que si", "KREH-oh keh see", "I think so", "Creo que si."),
    ("creo que no", "KREH-oh keh noh", "I don't think so", "Creo que no."),
    ("claro", "KLAH-roh", "of course/sure", "Claro que si!"),
    ("vale", "BAH-leh", "okay (Spain)", "Vale, nos vemos luego."),
    ("dale", "DAH-leh", "okay (Latin America)", "Dale, hagamoslo."),
    ("esta bien", "ehs-TAH byehn", "it's okay", "Esta bien, no te preocupes."),
    ("no hay problema", "noh ay proh-BLEH-mah", "no problem", "No hay problema."),
    ("no pasa nada", "noh PAH-sah NAH-dah", "it's nothing", "No pasa nada, tranquilo."),
    ("en serio", "ehn SEH-ryoh", "seriously?", "En serio? No lo puedo creer."),
    ("de verdad", "deh behr-DAHD", "really?", "De verdad? Que bien!"),
    ("que bien", "keh byehn", "how nice!", "Que bien que llegaste!"),
    ("que bueno", "keh BWEH-noh", "that's great", "Que bueno que viniste!"),
    ("que lastima", "keh LAHS-tee-mah", "what a pity", "Que lastima que no puedas venir."),
    ("que pena", "keh PEH-nah", "what a shame", "Que pena que paso eso."),
    ("que horror", "keh oh-RROHR", "how awful", "Que horror! Que paso?"),
    ("que rollo", "keh RROH-yoh", "what a drag", "Que rollo tener que esperar."),
    ("que lio", "keh LEE-oh", "what a mess", "Que lio se armo!"),
    ("que barbaridad", "keh bar-bah-ree-DAHD", "how outrageous", "Que barbaridad!"),
    ("no me digas", "noh meh DEE-gahs", "you don't say", "No me digas! En serio?"),
]
